# Verification of CamanhoDavilaTraction (and the shared BilinearMixedModeTraction
# base class) under pure-shear loading with delta_n = 0 throughout. This is the only
# scenario that exercises the compression-branch `delta_final_default = 2 * GIIc / S`
# path of BilinearMixedModeTraction, so it pins the energy identity
# 0.5 * S * delta_final = GIIc that the closed form requires.
#
# The reference time history (jumps and tractions) is generated by reference.py from
# the analytical pure-shear bilinear law and stored in reference.csv. VTestVerification
# checks every step. The companion verify_dissipation.py reads result.pt after the
# driver runs and confirms the integrated dissipation equals GIIc — a redundant
# end-to-end energy check, kept for reference.

[Tensors]
  [times]
    type = CSVScalar
    csv_file = 'reference.csv'
    column_names = 'time'
  []
  [jumps]
    type = CSVVec
    csv_file = 'reference.csv'
    column_names = 'delta_n delta_s1 delta_s2'
  []
  [tractions_ref]
    type = CSVVec
    csv_file = 'reference.csv'
    column_names = 'T_n T_s1 T_s2'
  []
[]

[Drivers]
  [driver]
    type = TransientDriver
    model = 'model'
    prescribed_time = 'times'
    force_Vec_names = 'separation'
    force_Vec_values = 'jumps'
    save_as = 'result.pt'
  []
  [verification]
    type = VTestVerification
    driver = 'driver'
    Vec_names = 'output.traction'
    Vec_values = 'tractions_ref'
    rtol = 1e-8
    # Pure-shear trajectory grazes d -> 1 near delta_final; tiny FP-reordering noise in delta_m
    # gets amplified through the (1 - d) factor, so absolute tractions differ from the analytical
    # reference by ~2e-10 on magnitudes of O(0.1). Relative agreement is still ~3e-9.
    atol = 1e-9
  []
[]

[Models]
  [decompose]
    type = VecComponents
    from = 'separation'
    to = 'signed_normal_separation tangential_separation_1 tangential_separation_2'
  []
  [tangential_separation]
    type = ScalarPNorm
    from = 'tangential_separation_1 tangential_separation_2'
    to = 'tangential_separation'
    exponent = 2.0
  []
  [macaulay_n]
    type = MacaulaySplit
    from = 'signed_normal_separation'
    to_positive = 'normal_separation'
    to_negative = 'normal_penetration'
  []
  [mode_mixity]
    type = ModeMixity
  []
  [critical_separation]
    type = CamanhoDavilaCriticalSeparation
    mode_mixity = 'mode_mixity'
    penalty_stiffness = 1000.0
    normal_strength = 10.0
    shear_strength = 15.0
  []
  [full_separation]
    type = BenzeggaghKenaneFullSeparation
    mode_mixity = 'mode_mixity'
    critical_separation = 'critical_separation'
    penalty_stiffness = 1000.0
    mode_I_fracture_toughness = 1.0
    mode_II_fracture_toughness = 2.0
    shear_strength = 15.0
    eta = 2.0
  []
  [effective_separation]
    type = ScalarPNorm
    from = 'normal_separation tangential_separation'
    to = 'effective_separation'
    exponent = 2.0
  []
  [traction]
    type = BilinearTraction
    critical_separation = 'critical_separation'
    full_separation = 'full_separation'
    normal_penetration = 'normal_penetration'
    penalty_stiffness = 1000.0
  []
  [model]
    type = ComposedModel
    models = 'decompose tangential_separation macaulay_n effective_separation traction'
  []
[]
