#!/usr/bin/env bash

${CMAKE_COMMAND} \
  -DCMAKE_POLICY_VERSION_MINIMUM=3.5 \
  -DCMAKE_GENERATOR="${CMAKE_GENERATOR}" \
  -DCMAKE_CXX_COMPILER="${CMAKE_CXX_COMPILER}" \
  -DCMAKE_CXX_FLAGS="-D_GLIBCXX_USE_CXX11_ABI=${GLIBCXX_USE_CXX11_ABI}" \
  -DCMAKE_BUILD_TYPE=Release \
  -DCMAKE_INSTALL_PREFIX="${INSTALL_PREFIX}" \
  -Dwasp_ENABLE_ALL_PACKAGES=OFF \
  -Dwasp_ENABLE_wasphit=ON \
  -Dwasp_ENABLE_testframework=OFF \
  -Dwasp_ENABLE_TESTS=OFF \
  -DBUILD_SHARED_LIBS=ON \
  -B"${BINARY_DIR}" \
  -S"${SOURCE_DIR}"


${CMAKE_COMMAND} --build "${BINARY_DIR}" --parallel "${NEML2_CONTRIB_PARALLEL}"
${CMAKE_COMMAND} --install "${BINARY_DIR}"
