#!/usr/bin/env bash

${CMAKE_COMMAND} \
  -DCMAKE_GENERATOR="${CMAKE_GENERATOR}" \
  -DCMAKE_CXX_COMPILER="${CMAKE_CXX_COMPILER}" \
  -DCMAKE_CXX_FLAGS="-D_GLIBCXX_USE_CXX11_ABI=${GLIBCXX_USE_CXX11_ABI}" \
  -DCMAKE_BUILD_TYPE=Release \
  -DCMAKE_INSTALL_PREFIX="${INSTALL_PREFIX}" \
  -DARGPARSE_BUILD_TESTS=OFF \
  -B"${BINARY_DIR}" \
  -S"${SOURCE_DIR}"

${CMAKE_COMMAND} --build "${BINARY_DIR}"
${CMAKE_COMMAND} --install "${BINARY_DIR}"
