# Verification of ExpTractionSeparation against the closed-form exponential damage law
# under a monotonic mixed-mode opening ramp. The reference time history (jumps and
# tractions) is generated by reference.py and stored in reference.csv. Under monotonic
# loading the irreversible-damage history collapses to the current effective separation,
# so the model output matches the analytical formula exactly.

[Tensors]
  [times]
    type = CSVScalar
    csv_file = 'reference.csv'
    column_names = 'time'
  []
  [jumps]
    type = CSVVec
    csv_file = 'reference.csv'
    column_names = 'delta_n delta_s1 delta_s2'
  []
  [tractions_ref]
    type = CSVVec
    csv_file = 'reference.csv'
    column_names = 'T_n T_s1 T_s2'
  []
[]

[Drivers]
  [driver]
    type = TransientDriver
    model = 'model'
    prescribed_time = 'times'
    force_Vec_names = 'displacement_jump'
    force_Vec_values = 'jumps'
    save_as = 'result.pt'
  []
  [verification]
    type = VTestVerification
    driver = 'driver'
    Vec_names = 'output.traction'
    Vec_values = 'tractions_ref'
    # Damage is path-dependent in general but path-independent for a monotonic ramp
    # (kappa = delta_eff at every step). The model evaluates the closed form in one shot,
    # so tight tolerances catch any sign / factor / wiring regression.
    rtol = 1e-10
    atol = 1e-12
  []
[]

[Models]
  [decompose]
    type = VecComponents
    from = 'displacement_jump'
    to = 'delta_n delta_s1 delta_s2'
  []
  [delta_eff]
    # Weighted Euclidean norm: sqrt(δ_n² + β_w (δ_s1² + δ_s2²) + ε), β_w = 1.0
    type = ScalarPNorm
    from = 'delta_n delta_s1 delta_s2'
    to = 'delta_eff'
    exponent = 2.0
    weights = '1.0 1.0 1.0'
  []
  [traction]
    type = ExponentialTraction
    effective_separation = 'delta_eff'
    normal_separation = 'delta_n'
    tangential_separation_1 = 'delta_s1'
    tangential_separation_2 = 'delta_s2'
    to = 'traction'
    damage = 'damage'
    fracture_toughness = 2.0
    characteristic_length = 1.0
  []
  [model]
    type = ComposedModel
    models = 'decompose delta_eff traction'
  []
[]
