var searchData=
[
  ['w_0',['W',['../classneml2_1_1crystallography_1_1CrystalGeometry.html#a513ecb69529b1e45d7927050805ea4fc',1,'neml2::crystallography::CrystalGeometry']]],
  ['wait_5ffor_5fcompletion_1',['wait_for_completion',['../classneml2_1_1WorkScheduler.html#a4cb81aa2a0c00c9262ac0b45ed0031ef',1,'neml2::WorkScheduler']]],
  ['way_2',['way',['../tutorials-models-model-composition.html#autotoc_md108',1,'Evaluating the models: The easy way'],['../tutorials-models-model-composition.html#autotoc_md107',1,'Evaluating the models: The hard way']]],
  ['wffr4_3',['WFFR4',['../classneml2_1_1WFFR4.html',1,'WFFR4'],['../syntax-tensors.html#wffr4',1,'WFFR4']]],
  ['wffr4constantparameter_4',['WFFR4ConstantParameter',['../syntax-models.html#wffr4constantparameter',1,'']]],
  ['wffr4dynamicmean_5',['WFFR4DynamicMean',['../syntax-models.html#wffr4dynamicmean',1,'']]],
  ['wffr4dynamicsum_6',['WFFR4DynamicSum',['../syntax-models.html#wffr4dynamicsum',1,'']]],
  ['wffr4fromtorchscript_7',['WFFR4FromTorchScript',['../syntax-tensors.html#wffr4fromtorchscript',1,'']]],
  ['wffr4inputparameter_8',['WFFR4InputParameter',['../syntax-models.html#wffr4inputparameter',1,'']]],
  ['wffr4intermediatemean_9',['WFFR4IntermediateMean',['../syntax-models.html#wffr4intermediatemean',1,'']]],
  ['wffr4intermediatesum_10',['WFFR4IntermediateSum',['../syntax-models.html#wffr4intermediatesum',1,'']]],
  ['wffr4parametertostate_11',['WFFR4ParameterToState',['../syntax-models.html#wffr4parametertostate',1,'']]],
  ['what_12',['what',['../classneml2_1_1NEMLException.html#abf843cbb29dec939d0731e491bab6f70',1,'neml2::NEMLException::what()'],['../classneml2_1_1SetupException.html#abf843cbb29dec939d0731e491bab6f70',1,'neml2::SetupException::what()']]],
  ['what_20is_20vectorization_13',['What is vectorization?',['../tutorials-models-vectorization.html#autotoc_md127',1,'']]],
  ['who_20touched_20my_20data_14',['Who touched my data?',['../tutorials-tensors-tensor-view.html#autotoc_md155',1,'']]],
  ['why_20batching_15',['Why batching?',['../tutorials-tensors-tensor-types.html#autotoc_md152',1,'']]],
  ['with_20tensors_16',['Working with tensors',['../system-tensors.html#working-with-tensors',1,'']]],
  ['with_5fsuffix_17',['with_suffix',['../classneml2_1_1LabeledAxisAccessor.html#a68aee86962a6ea2deef39fd6a9f86a4c',1,'neml2::LabeledAxisAccessor']]],
  ['work_20dispatchers_18',['Work dispatchers',['../system-schedulers.html#autotoc_md59',1,'']]],
  ['work_20schedulers_19',['Work schedulers',['../system-schedulers.html#autotoc_md60',1,'']]],
  ['workdispatcher_20',['WorkDispatcher',['../classneml2_1_1WorkDispatcher.html',1,'WorkDispatcher&lt; I, O, Of, Ip, Op &gt;'],['../classneml2_1_1WorkDispatcher.html#ae1a08465b7e029397b37ffee409958be',1,'neml2::WorkDispatcher::WorkDispatcher(WorkScheduler &amp;scheduler, bool async, std::function&lt; O(I &amp;&amp;, Device)&gt; &amp;&amp;do_work)'],['../classneml2_1_1WorkDispatcher.html#af7b929c0c59187034ccc1978da6568cc',1,'neml2::WorkDispatcher::WorkDispatcher(WorkScheduler &amp;scheduler, bool async, std::function&lt; O(I &amp;&amp;, Device)&gt; &amp;&amp;do_work, std::function&lt; O(std::vector&lt; O &gt; &amp;&amp;)&gt; &amp;&amp;reduce)'],['../classneml2_1_1WorkDispatcher.html#a810fc127bf632decdc30032759c70cad',1,'neml2::WorkDispatcher::WorkDispatcher(WorkScheduler &amp;scheduler, bool async, std::function&lt; O(I &amp;&amp;, Device)&gt; &amp;&amp;do_work, std::function&lt; Of(std::vector&lt; Op &gt; &amp;&amp;)&gt; &amp;&amp;reduce, std::function&lt; I(Ip &amp;&amp;, Device)&gt; &amp;&amp;preprocess, std::function&lt; Op(O &amp;&amp;)&gt; &amp;&amp;postprocess)'],['../classneml2_1_1WorkDispatcher.html#a94ad3091d7c628adf71fe4667627ecdd',1,'neml2::WorkDispatcher::WorkDispatcher(WorkScheduler &amp;scheduler, bool async, std::function&lt; O(I &amp;&amp;, Device)&gt; &amp;&amp;do_work, std::function&lt; Of(std::vector&lt; Op &gt; &amp;&amp;)&gt; &amp;&amp;reduce, std::function&lt; I(Ip &amp;&amp;, Device)&gt; &amp;&amp;preprocess, std::function&lt; Op(O &amp;&amp;)&gt; &amp;&amp;postprocess, std::function&lt; void(Device)&gt; &amp;&amp;thread_init)'],['../classneml2_1_1WorkDispatcher.html#ad3f9fdb587f99cba965f43bed8f77ff0',1,'neml2::WorkDispatcher::WorkDispatcher()=delete'],['../classneml2_1_1WorkDispatcher.html#ac1f7e9ee1e6490803b17f0065165d6c7',1,'neml2::WorkDispatcher::WorkDispatcher(WorkDispatcher &amp;&amp;)=delete'],['../classneml2_1_1WorkDispatcher.html#a5048656ba7bab44f6f0e8f5f8e771aef',1,'neml2::WorkDispatcher::WorkDispatcher(const WorkDispatcher &amp;)=delete']]],
  ['workgenerator_21',['WorkGenerator',['../classneml2_1_1WorkGenerator.html',1,'WorkGenerator&lt; T &gt;'],['../classneml2_1_1WorkGenerator.html#a5db2041b0c5eca88c232fb16c21af435',1,'neml2::WorkGenerator::WorkGenerator()=default'],['../classneml2_1_1WorkGenerator.html#af9233b23b58d4b4048655637758c7c2f',1,'neml2::WorkGenerator::WorkGenerator(WorkGenerator &amp;&amp;) noexcept=default'],['../classneml2_1_1WorkGenerator.html#a85d746638d58fc271ad148ebd9e2d4dc',1,'neml2::WorkGenerator::WorkGenerator(const WorkGenerator &amp;)=default']]],
  ['workgenerator_3c_20indexing_3a_3aslice_20_3e_22',['WorkGenerator&lt; indexing::Slice &gt;',['../classneml2_1_1WorkGenerator.html',1,'neml2']]],
  ['workgenerator_3c_20tensor_20_3e_23',['WorkGenerator&lt; Tensor &gt;',['../classneml2_1_1WorkGenerator.html',1,'neml2']]],
  ['workgenerator_3c_20valuemap_20_3e_24',['WorkGenerator&lt; ValueMap &gt;',['../classneml2_1_1WorkGenerator.html',1,'neml2']]],
  ['working_20with_20tensors_25',['Working with tensors',['../system-tensors.html#working-with-tensors',1,'']]],
  ['workscheduler_26',['WorkScheduler',['../classneml2_1_1WorkScheduler.html',1,'WorkScheduler'],['../classneml2_1_1WorkScheduler.html#acb5d9b56c644b203bf2c14b56e1b06ee',1,'neml2::WorkScheduler::WorkScheduler()']]],
  ['wr2_27',['WR2',['../classneml2_1_1WR2.html',1,'WR2'],['../classneml2_1_1WR2.html#a6cb43b5cdc34ea2c3ce3043766148081',1,'neml2::WR2::WR2()'],['../syntax-tensors.html#wr2',1,'WR2']]],
  ['wr2constantparameter_28',['WR2ConstantParameter',['../syntax-models.html#wr2constantparameter',1,'']]],
  ['wr2dynamicmean_29',['WR2DynamicMean',['../syntax-models.html#wr2dynamicmean',1,'']]],
  ['wr2dynamicsum_30',['WR2DynamicSum',['../syntax-models.html#wr2dynamicsum',1,'']]],
  ['wr2explicitexponentialtimeintegration_31',['WR2ExplicitExponentialTimeIntegration',['../classneml2_1_1WR2ExplicitExponentialTimeIntegration.html',1,'WR2ExplicitExponentialTimeIntegration'],['../classneml2_1_1WR2ExplicitExponentialTimeIntegration.html#a87b18f571db9bc8b7cc36280b1e9c485',1,'neml2::WR2ExplicitExponentialTimeIntegration::WR2ExplicitExponentialTimeIntegration()'],['../syntax-models.html#wr2explicitexponentialtimeintegration',1,'WR2ExplicitExponentialTimeIntegration']]],
  ['wr2fromtorchscript_32',['WR2FromTorchScript',['../syntax-tensors.html#wr2fromtorchscript',1,'']]],
  ['wr2implicitexponentialtimeintegration_33',['WR2ImplicitExponentialTimeIntegration',['../classneml2_1_1WR2ImplicitExponentialTimeIntegration.html',1,'WR2ImplicitExponentialTimeIntegration'],['../classneml2_1_1WR2ImplicitExponentialTimeIntegration.html#a4659fde107d6570a0870675b509edffd',1,'neml2::WR2ImplicitExponentialTimeIntegration::WR2ImplicitExponentialTimeIntegration()'],['../syntax-models.html#wr2implicitexponentialtimeintegration',1,'WR2ImplicitExponentialTimeIntegration']]],
  ['wr2inputparameter_34',['WR2InputParameter',['../syntax-models.html#wr2inputparameter',1,'']]],
  ['wr2intermediatemean_35',['WR2IntermediateMean',['../syntax-models.html#wr2intermediatemean',1,'']]],
  ['wr2intermediatesum_36',['WR2IntermediateSum',['../syntax-models.html#wr2intermediatesum',1,'']]],
  ['wr2parametertostate_37',['WR2ParameterToState',['../syntax-models.html#wr2parametertostate',1,'']]],
  ['wrapping_20a_20torch_20tensor_38',['Wrapping a torch tensor',['../tutorials-tensors-tensor-creation.html#autotoc_md149',1,'']]],
  ['writing_20the_20input_20file_39',['Writing the input file',['../tutorials-models-model-composition.html#autotoc_md106',1,'Writing the input file'],['../tutorials-models-running-your-first-model.html#autotoc_md120',1,'Writing the input file']]],
  ['wsr4_40',['WSR4',['../classneml2_1_1WSR4.html',1,'WSR4'],['../classneml2_1_1WSR4.html#a5ed8a8dad51cca66ccaa68c5191990a1',1,'neml2::WSR4::WSR4()'],['../syntax-tensors.html#wsr4',1,'WSR4']]],
  ['wsr4constantparameter_41',['WSR4ConstantParameter',['../syntax-models.html#wsr4constantparameter',1,'']]],
  ['wsr4dynamicmean_42',['WSR4DynamicMean',['../syntax-models.html#wsr4dynamicmean',1,'']]],
  ['wsr4dynamicsum_43',['WSR4DynamicSum',['../syntax-models.html#wsr4dynamicsum',1,'']]],
  ['wsr4fromtorchscript_44',['WSR4FromTorchScript',['../syntax-tensors.html#wsr4fromtorchscript',1,'']]],
  ['wsr4inputparameter_45',['WSR4InputParameter',['../syntax-models.html#wsr4inputparameter',1,'']]],
  ['wsr4intermediatemean_46',['WSR4IntermediateMean',['../syntax-models.html#wsr4intermediatemean',1,'']]],
  ['wsr4intermediatesum_47',['WSR4IntermediateSum',['../syntax-models.html#wsr4intermediatesum',1,'']]],
  ['wsr4parametertostate_48',['WSR4ParameterToState',['../syntax-models.html#wsr4parametertostate',1,'']]],
  ['wwr4_49',['WWR4',['../classneml2_1_1WWR4.html',1,'WWR4'],['../classneml2_1_1WWR4.html#adc28cfde0ac29bb8956d8c29ef76438b',1,'neml2::WWR4::WWR4()'],['../syntax-tensors.html#wwr4',1,'WWR4']]],
  ['wwr4constantparameter_50',['WWR4ConstantParameter',['../syntax-models.html#wwr4constantparameter',1,'']]],
  ['wwr4dynamicmean_51',['WWR4DynamicMean',['../syntax-models.html#wwr4dynamicmean',1,'']]],
  ['wwr4dynamicsum_52',['WWR4DynamicSum',['../syntax-models.html#wwr4dynamicsum',1,'']]],
  ['wwr4fromtorchscript_53',['WWR4FromTorchScript',['../syntax-tensors.html#wwr4fromtorchscript',1,'']]],
  ['wwr4inputparameter_54',['WWR4InputParameter',['../syntax-models.html#wwr4inputparameter',1,'']]],
  ['wwr4intermediatemean_55',['WWR4IntermediateMean',['../syntax-models.html#wwr4intermediatemean',1,'']]],
  ['wwr4intermediatesum_56',['WWR4IntermediateSum',['../syntax-models.html#wwr4intermediatesum',1,'']]],
  ['wwr4parametertostate_57',['WWR4ParameterToState',['../syntax-models.html#wwr4parametertostate',1,'']]]
];
