var searchData=
[
  ['data_0',['Data',['../syntax-data.html',1,'[Data]'],['../system-data.html',1,'Data'],['../system-data.html#autotoc_md65',1,'Data']]],
  ['data_1',['data',['../python-examples-deterministic.html#autotoc_md183',1,'Calibrate the model against the synthetic data'],['../python-examples-deterministic.html#autotoc_md179',1,'Plot the synthetic data'],['../python-examples-statistical.html#autotoc_md195',1,'Plot the synthetic data'],['../python-examples-deterministic.html#autotoc_md178',1,'Run the model to generate the synthetic data'],['../python-examples-statistical.html#autotoc_md194',1,'Run the model to generate the synthetic data'],['../tutorials-tensors-tensor-view.html#autotoc_md217',1,'Who touched my data?']]],
  ['data_20and_20for_20our_20initial_20guess_20at_20the_20parameters_2',['data and for our initial guess at the parameters',['../python-examples-deterministic.html#autotoc_md173',1,'Define the variability in the synthetic data and for our initial guess at the parameters'],['../python-examples-statistical.html#autotoc_md189',1,'Define the variability in the synthetic data and for our initial guess at the parameters']]],
  ['data_20scarcity_3',['Challenge 2: Data scarcity',['../tutorials-optimization-pyzag.html#autotoc_md153',1,'']]],
  ['declaration_4',['declaration',['../tutorials-extension-argument-declaration.html',1,'Argument declaration'],['../tutorials-extension-argument-declaration.html#autotoc_md86',1,'Parameter declaration'],['../tutorials-extension-argument-declaration.html#autotoc_md85',1,'Variable declaration']]],
  ['define_20the_20variability_20in_20the_20synthetic_20data_20and_20for_20our_20initial_20guess_20at_20the_20parameters_5',['Define the variability in the synthetic data and for our initial guess at the parameters',['../python-examples-deterministic.html#autotoc_md173',1,'Define the variability in the synthetic data and for our initial guess at the parameters'],['../python-examples-statistical.html#autotoc_md189',1,'Define the variability in the synthetic data and for our initial guess at the parameters']]],
  ['defining_20the_20system_20of_20equations_6',['Defining the system of equations',['../tutorials-models-implicit-model.html#autotoc_md108',1,'']]],
  ['definition_7',['definition',['../system-models.html#model-definition',1,'Model definition'],['../tutorials-optimization-automatic-differentiation.html#autotoc_md148',1,'Model definition'],['../tutorials-extension-model-composition.html#autotoc_md95',1,'Problem definition'],['../tutorials-optimization-parameter-calibration.html#autotoc_md150',1,'Problem definition']]],
  ['deformation_8',['Simulate rolling deformation',['../python-examples-crystal_plasticity-polefigures.html#autotoc_md167',1,'']]],
  ['deformation_20for_20the_20seperated_20model_9',['Simulate rolling deformation for the seperated model',['../python-examples-crystal_plasticity-compare_formulations.html#autotoc_md157',1,'']]],
  ['degradation_20functions_10',['Degradation functions',['../phase-field-fracture.html#autotoc_md31',1,'']]],
  ['denselu_11',['DenseLU',['../syntax-solvers.html#denselu',1,'']]],
  ['density_12',['Strain Energy Density',['../phase-field-fracture.html#autotoc_md32',1,'']]],
  ['dependencies_13',['dependencies',['../dependency-management.html#autotoc_md10',1,'List of dependencies'],['../dependency-management.html#autotoc_md11',1,'Skipping dependencies']]],
  ['dependency_20management_14',['Dependency management',['../dependency-management.html',1,'']]],
  ['dependency_20registration_15',['Automatic dependency registration',['../system-models.html#automatic-dependency-registration',1,'']]],
  ['dependency_20resolution_16',['Automatic dependency resolution',['../system-models.html#automatic-dependency-resolution',1,'']]],
  ['dependency_20search_17',['Dependency search',['../dependency-management.html#autotoc_md9',1,'']]],
  ['derivatives_20of_20recursive_20nonlinear_20functions_18',['Challenge 1: Obtaining parameter derivatives of recursive nonlinear functions',['../tutorials-optimization-pyzag.html#autotoc_md152',1,'']]],
  ['description_19',['description',['../tutorials-extension.html#autotoc_md92',1,'Problem description'],['../tutorials-models-implicit-model.html#autotoc_md107',1,'Problem description'],['../tutorials-models-just-in-time-compilation.html#autotoc_md112',1,'Problem description'],['../tutorials-models-model-composition.html#autotoc_md117',1,'Problem description'],['../tutorials-models-model-parameters.html#autotoc_md121',1,'Problem description'],['../tutorials-models-model-parameters-revisited.html#autotoc_md125',1,'Problem description'],['../tutorials-models-running-your-first-model.html#autotoc_md130',1,'Problem description'],['../tutorials-models-transient-driver.html#autotoc_md137',1,'Problem description']]],
  ['design_20philosophy_20',['Features and design philosophy',['../index.html#autotoc_md4',1,'']]],
  ['details_21',['details',['../reactive-infiltration.html#autotoc_md36',1,'Implementation details'],['../thermosetting-pyrolysis.html#autotoc_md54',1,'Implementation details']]],
  ['deterministic_20material_20model_20calibration_22',['Deterministic material model calibration',['../python-examples-deterministic.html',1,'']]],
  ['development_23',['Model development',['../tutorials-contributing.html#autotoc_md79',1,'']]],
  ['device_24',['Device',['../tutorials-models-evaluation-device.html#autotoc_md104',1,'']]],
  ['device_25',['device',['../tutorials-models-evaluation-device.html#autotoc_md106',1,'Evaluating the model on a different device'],['../tutorials-models-evaluation-device.html',1,'Evaluation device'],['../tutorials-models-evaluation-device.html#autotoc_md105',1,'Specifying a device']]],
  ['differencemillerindex_26',['DifferenceMillerIndex',['../syntax-tensors.html#differencemillerindex',1,'']]],
  ['differencequaternion_27',['DifferenceQuaternion',['../syntax-tensors.html#differencequaternion',1,'']]],
  ['differencer2_28',['DifferenceR2',['../syntax-tensors.html#differencer2',1,'']]],
  ['differencer3_29',['DifferenceR3',['../syntax-tensors.html#differencer3',1,'']]],
  ['differencer4_30',['DifferenceR4',['../syntax-tensors.html#differencer4',1,'']]],
  ['differencerot_31',['DifferenceRot',['../syntax-tensors.html#differencerot',1,'']]],
  ['differencescalar_32',['DifferenceScalar',['../syntax-tensors.html#differencescalar',1,'']]],
  ['differencesffr4_33',['DifferenceSFFR4',['../syntax-tensors.html#differencesffr4',1,'']]],
  ['differencesfr3_34',['DifferenceSFR3',['../syntax-tensors.html#differencesfr3',1,'']]],
  ['differencesr2_35',['DifferenceSR2',['../syntax-tensors.html#differencesr2',1,'']]],
  ['differencessr4_36',['DifferenceSSR4',['../syntax-tensors.html#differencessr4',1,'']]],
  ['differenceswr4_37',['DifferenceSWR4',['../syntax-tensors.html#differenceswr4',1,'']]],
  ['differencetensor_38',['DifferenceTensor',['../syntax-tensors.html#differencetensor',1,'']]],
  ['differencevec_39',['DifferenceVec',['../syntax-tensors.html#differencevec',1,'']]],
  ['differencewffr4_40',['DifferenceWFFR4',['../syntax-tensors.html#differencewffr4',1,'']]],
  ['differencewr2_41',['DifferenceWR2',['../syntax-tensors.html#differencewr2',1,'']]],
  ['differencewsr4_42',['DifferenceWSR4',['../syntax-tensors.html#differencewsr4',1,'']]],
  ['differencewwr4_43',['DifferenceWWR4',['../syntax-tensors.html#differencewwr4',1,'']]],
  ['different_20device_44',['Evaluating the model on a different device',['../tutorials-models-evaluation-device.html#autotoc_md106',1,'']]],
  ['differentiation_45',['differentiation',['../tutorials-optimization-automatic-differentiation.html',1,'Automatic differentiation'],['../system-models.html#automatic-differentiation',1,'Automatic differentiation'],['../tutorials-optimization-automatic-differentiation.html#autotoc_md149',1,'Automatic differentiation']]],
  ['diffusionlimitedreaction_46',['DiffusionLimitedReaction',['../syntax-models.html#diffusionlimitedreaction',1,'']]],
  ['dimensional_20indexing_20tools_47',['Dimensional indexing tools',['../tutorials-tensors-indexing.html#autotoc_md210',1,'']]],
  ['directory_48',['Sub-directory',['../external-project-integration.html#autotoc_md17',1,'']]],
  ['discrete_20pole_20figure_49',['Plot a discrete pole figure',['../python-examples-crystal_plasticity-polefigures.html#autotoc_md168',1,'']]],
  ['discretization_50',['Finite volume discretization',['../finite-volume.html#autotoc_md23',1,'']]],
  ['dislocationobstaclestrengthmap_51',['DislocationObstacleStrengthMap',['../syntax-models.html#dislocationobstaclestrengthmap',1,'']]],
  ['dispatchers_52',['Work dispatchers',['../system-schedulers.html#autotoc_md71',1,'']]],
  ['documentation_53',['Documentation',['../tutorials-contributing.html#autotoc_md83',1,'']]],
  ['downstream_20c_20project_54',['Downstream C++ project',['../tutorials-getting-started.html#autotoc_md101',1,'']]],
  ['driver_55',['Driver',['../system-drivers.html',1,'']]],
  ['driver_56',['driver',['../python-examples-crystal_plasticity-polefigures.html#autotoc_md166',1,'pyzag driver'],['../tutorials-models-transient-driver.html',1,'Transient driver']]],
  ['driver_20for_20the_20integrated_20model_57',['pyzag driver for the integrated model',['../python-examples-crystal_plasticity-compare_formulations.html#autotoc_md159',1,'']]],
  ['driver_20for_20the_20separated_20model_58',['pyzag driver for the separated model',['../python-examples-crystal_plasticity-compare_formulations.html#autotoc_md156',1,'']]],
  ['drivers_59',['[Drivers]',['../syntax-drivers.html',1,'']]],
  ['dynamically_20shaped_20tensor_60',['Dynamically shaped tensor',['../system-tensors.html#dynamically-shaped-tensor',1,'']]]
];
