var searchData=
[
  ['package_0',['package',['../install.html#autotoc_md14',1,'Python package'],['../tutorials-contributing.html#autotoc_md81',1,'Python package']]],
  ['parameter_20calibration_1',['Parameter calibration',['../tutorials-optimization-parameter-calibration.html',1,'']]],
  ['parameter_20declaration_2',['Parameter declaration',['../tutorials-extension-argument-declaration.html#autotoc_md86',1,'']]],
  ['parameter_20derivatives_20of_20recursive_20nonlinear_20functions_3',['Challenge 1: Obtaining parameter derivatives of recursive nonlinear functions',['../tutorials-optimization-pyzag.html#autotoc_md152',1,'']]],
  ['parameter_20specification_4',['Parameter specification',['../tutorials-models-model-parameters-revisited.html#autotoc_md126',1,'']]],
  ['parameter_20value_5',['parameter value',['../tutorials-models-model-parameters.html#autotoc_md123',1,'Retrieving the parameter value'],['../tutorials-models-model-parameters.html#autotoc_md124',1,'Updating the parameter value']]],
  ['parameter_20values_6',['Run the model with the initial parameter values',['../python-examples-deterministic.html#autotoc_md182',1,'']]],
  ['parameter_20vs_20buffer_7',['Parameter vs buffer',['../tutorials-models-model-parameters.html#autotoc_md122',1,'']]],
  ['parameters_8',['parameters',['../python-examples-deterministic.html#autotoc_md173',1,'Define the variability in the synthetic data and for our initial guess at the parameters'],['../python-examples-statistical.html#autotoc_md189',1,'Define the variability in the synthetic data and for our initial guess at the parameters'],['../tutorials-models-model-parameters.html',1,'Model parameters'],['../python-examples-deterministic.html#autotoc_md181',1,'Scale the model parameters'],['../python-examples-statistical.html#autotoc_md198',1,'Scale the model parameters']]],
  ['parameters_20related_20to_20how_20we_20calibrate_20the_20model_9',['Setup parameters related to &lt;em&gt;how&lt;/em&gt; we calibrate the model',['../python-examples-deterministic.html#autotoc_md171',1,'']]],
  ['parameters_20related_20to_20how_20we_20train_20the_20model_10',['Setup parameters related to &lt;em&gt;how&lt;/em&gt; we train the model',['../python-examples-statistical.html#autotoc_md186',1,'']]],
  ['parameters_20revisited_11',['Model parameters (revisited)',['../tutorials-models-model-parameters-revisited.html',1,'']]],
  ['parameters_20with_20random_20values_12',['parameters with random values',['../python-examples-deterministic.html#autotoc_md177',1,'Replace the model parameters with random values'],['../python-examples-statistical.html#autotoc_md193',1,'Replace the model parameters with random values']]],
  ['parser_13',['Parser',['../tutorials-extension-connection-to-input-files.html#autotoc_md88',1,'']]],
  ['perfectly_20plastic_20yield_20function_14',['Perfectly Plastic Yield function',['../solid-mechanics.html#autotoc_md43',1,'']]],
  ['perslipforestdislocationevolution_15',['PerSlipForestDislocationEvolution',['../syntax-models.html#perslipforestdislocationevolution',1,'']]],
  ['perzynaplasticflowrate_16',['PerzynaPlasticFlowRate',['../syntax-models.html#perzynaplasticflowrate',1,'']]],
  ['phase_20field_20fracture_17',['Phase-Field Fracture',['../phase-field-fracture.html',1,'']]],
  ['phasetransformationeigenstrain_18',['PhaseTransformationEigenstrain',['../syntax-models.html#phasetransformationeigenstrain',1,'']]],
  ['philosophy_19',['Features and design philosophy',['../index.html#autotoc_md4',1,'']]],
  ['physics_20',['Finite Volume Transport Physics',['../finite-volume.html',1,'']]],
  ['plain_20numeric_20literal_21',['Plain numeric literal',['../tutorials-models-model-parameters-revisited.html#autotoc_md127',1,'']]],
  ['plastic_20yield_20function_22',['Perfectly Plastic Yield function',['../solid-mechanics.html#autotoc_md43',1,'']]],
  ['plasticdeformationrate_23',['PlasticDeformationRate',['../syntax-models.html#plasticdeformationrate',1,'']]],
  ['plasticity_24',['plasticity',['../solid-mechanics.html#autotoc_md40',1,'Consistent plasticity'],['../solid-mechanics.html#autotoc_md50',1,'Crystal plasticity']]],
  ['plasticity_20formulations_25',['Crystal plasticity formulations',['../python-examples-crystal_plasticity-compare_formulations.html',1,'']]],
  ['plasticity_20macroscale_26',['Plasticity (macroscale)',['../solid-mechanics.html#autotoc_md39',1,'']]],
  ['plasticspatialvelocitygradient_27',['PlasticSpatialVelocityGradient',['../syntax-models.html#plasticspatialvelocitygradient',1,'']]],
  ['plasticvorticity_28',['PlasticVorticity',['../syntax-models.html#plasticvorticity',1,'']]],
  ['plot_20a_20continuous_20polefigure_29',['Plot a continuous polefigure',['../python-examples-crystal_plasticity-polefigures.html#autotoc_md170',1,'']]],
  ['plot_20a_20discrete_20pole_20figure_30',['Plot a discrete pole figure',['../python-examples-crystal_plasticity-polefigures.html#autotoc_md168',1,'']]],
  ['plot_20some_20comparisons_20of_20the_20elastic_20strains_31',['Plot some comparisons of the elastic strains',['../python-examples-crystal_plasticity-compare_formulations.html#autotoc_md164',1,'']]],
  ['plot_20the_20calibrated_20model_20predictions_32',['Plot the calibrated model predictions',['../python-examples-deterministic.html#autotoc_md184',1,'']]],
  ['plot_20the_20pole_20figures_33',['Plot the pole figures',['../python-examples-crystal_plasticity-compare_formulations.html#autotoc_md163',1,'']]],
  ['plot_20the_20synthetic_20data_34',['Plot the synthetic data',['../python-examples-deterministic.html#autotoc_md179',1,'Plot the synthetic data'],['../python-examples-statistical.html#autotoc_md195',1,'Plot the synthetic data']]],
  ['plotting_20polefigures_35',['Plotting polefigures',['../python-examples-crystal_plasticity-polefigures.html',1,'']]],
  ['pole_20figure_36',['Plot a discrete pole figure',['../python-examples-crystal_plasticity-polefigures.html#autotoc_md168',1,'']]],
  ['pole_20figures_37',['Plot the pole figures',['../python-examples-crystal_plasticity-compare_formulations.html#autotoc_md163',1,'']]],
  ['polefigure_38',['Plot a continuous polefigure',['../python-examples-crystal_plasticity-polefigures.html#autotoc_md170',1,'']]],
  ['polefigures_39',['Plotting polefigures',['../python-examples-crystal_plasticity-polefigures.html',1,'']]],
  ['posteriors_40',['Compare priors, true posteriors, and inferred posteriors',['../python-examples-statistical.html#autotoc_md204',1,'']]],
  ['posteriors_20and_20inferred_20posteriors_41',['Compare priors, true posteriors, and inferred posteriors',['../python-examples-statistical.html#autotoc_md204',1,'']]],
  ['powerdegradationfunction_42',['PowerDegradationFunction',['../syntax-models.html#powerdegradationfunction',1,'']]],
  ['powerlawisotropichardeningstaticrecovery_43',['PowerLawIsotropicHardeningStaticRecovery',['../syntax-models.html#powerlawisotropichardeningstaticrecovery',1,'']]],
  ['powerlawkinematichardeningstaticrecovery_44',['PowerLawKinematicHardeningStaticRecovery',['../syntax-models.html#powerlawkinematichardeningstaticrecovery',1,'']]],
  ['powerlawpermeability_45',['PowerLawPermeability',['../syntax-models.html#powerlawpermeability',1,'']]],
  ['powerlawsliprule_46',['PowerLawSlipRule',['../syntax-models.html#powerlawsliprule',1,'']]],
  ['predictions_47',['Plot the calibrated model predictions',['../python-examples-deterministic.html#autotoc_md184',1,'']]],
  ['prerequisites_48',['Prerequisites',['../install.html#autotoc_md12',1,'']]],
  ['presets_49',['presets',['../build-customization.html#autotoc_md8',1,'Build presets'],['../build-customization.html#autotoc_md7',1,'Configure presets']]],
  ['print_20the_20calibrated_20model_20coefficients_50',['Print the calibrated model coefficients',['../python-examples-deterministic.html#autotoc_md185',1,'']]],
  ['prior_20model_20to_20compare_20to_20the_20repeated_20test_51',['Sample the prior model to compare to the repeated test',['../python-examples-statistical.html#autotoc_md200',1,'']]],
  ['priors_20true_20posteriors_20and_20inferred_20posteriors_52',['Compare priors, true posteriors, and inferred posteriors',['../python-examples-statistical.html#autotoc_md204',1,'']]],
  ['problem_20definition_53',['Problem definition',['../tutorials-extension-model-composition.html#autotoc_md95',1,'Problem definition'],['../tutorials-optimization-parameter-calibration.html#autotoc_md150',1,'Problem definition']]],
  ['problem_20description_54',['Problem description',['../tutorials-extension.html#autotoc_md92',1,'Problem description'],['../tutorials-models-implicit-model.html#autotoc_md107',1,'Problem description'],['../tutorials-models-just-in-time-compilation.html#autotoc_md112',1,'Problem description'],['../tutorials-models-model-composition.html#autotoc_md117',1,'Problem description'],['../tutorials-models-model-parameters.html#autotoc_md121',1,'Problem description'],['../tutorials-models-model-parameters-revisited.html#autotoc_md125',1,'Problem description'],['../tutorials-models-running-your-first-model.html#autotoc_md130',1,'Problem description'],['../tutorials-models-transient-driver.html#autotoc_md137',1,'Problem description']]],
  ['project_55',['Downstream C++ project',['../tutorials-getting-started.html#autotoc_md101',1,'']]],
  ['project_20integration_56',['External Project Integration',['../external-project-integration.html',1,'']]],
  ['projectiles_57',['Lauching the projectiles',['../tutorials-extension-model-composition.html#autotoc_md97',1,'']]],
  ['pyrolysis_58',['Thermosetting Pyrolysis',['../thermosetting-pyrolysis.html',1,'']]],
  ['pytest_59',['pytest',['../tutorials-contributing.html#testing-pytest',1,'']]],
  ['python_20package_60',['Python package',['../install.html#autotoc_md14',1,'Python package'],['../tutorials-contributing.html#autotoc_md81',1,'Python package']]],
  ['python_20script_61',['Python script',['../tutorials-getting-started.html#autotoc_md103',1,'']]],
  ['python_20stubs_62',['Python stubs',['../tutorials-contributing.html#testing-python-stubs',1,'']]],
  ['pyzag_63',['pyzag',['../tutorials-optimization-pyzag.html',1,'']]],
  ['pyzag_20driver_64',['pyzag driver',['../python-examples-crystal_plasticity-polefigures.html#autotoc_md166',1,'']]],
  ['pyzag_20driver_20for_20the_20integrated_20model_65',['pyzag driver for the integrated model',['../python-examples-crystal_plasticity-compare_formulations.html#autotoc_md159',1,'']]],
  ['pyzag_20driver_20for_20the_20separated_20model_66',['pyzag driver for the separated model',['../python-examples-crystal_plasticity-compare_formulations.html#autotoc_md156',1,'']]]
];
