var searchData=
[
  ['a_20continuous_20polefigure_0',['Plot a continuous polefigure',['../python-examples-crystal_plasticity-polefigures.html#autotoc_md170',1,'']]],
  ['a_20device_1',['Specifying a device',['../tutorials-models-evaluation-device.html#autotoc_md105',1,'']]],
  ['a_20different_20device_2',['Evaluating the model on a different device',['../tutorials-models-evaluation-device.html#autotoc_md106',1,'']]],
  ['a_20discrete_20pole_20figure_3',['Plot a discrete pole figure',['../python-examples-crystal_plasticity-polefigures.html#autotoc_md168',1,'']]],
  ['a_20fixed_20condition_4',['Now sample at run at a fixed condition',['../python-examples-statistical.html#autotoc_md196',1,'']]],
  ['a_20guide_20and_20training_20hyperparameters_5',['Setup a guide and training hyperparameters',['../python-examples-statistical.html#autotoc_md201',1,'']]],
  ['a_20hierarchical_20statistical_20model_6',['Convert the model to a hierarchical statistical model',['../python-examples-statistical.html#autotoc_md199',1,'']]],
  ['a_20model_20from_20the_20input_20file_7',['Loading a model from the input file',['../tutorials-models-running-your-first-model.html#autotoc_md134',1,'']]],
  ['a_20numerical_20experiment_8',['For loop versus vectorization: A numerical experiment',['../tutorials-models-vectorization.html#autotoc_md140',1,'']]],
  ['a_20symbolic_20example_9',['A symbolic example',['../system-models.html#a-symbolic-example',1,'']]],
  ['a_20torch_20tensor_10',['Wrapping a torch tensor',['../tutorials-tensors-tensor-creation.html#autotoc_md211',1,'']]],
  ['actual_20model_11',['actual model',['../python-examples-deterministic.html#autotoc_md174',1,'Setup the actual model'],['../python-examples-statistical.html#autotoc_md190',1,'Setup the actual model']]],
  ['actually_20setup_20the_20model_12',['Actually setup the model',['../python-examples-deterministic.html#autotoc_md175',1,'Actually setup the model'],['../python-examples-statistical.html#autotoc_md191',1,'Actually setup the model']]],
  ['advanced_20tutorials_13',['Advanced tutorials',['../tutorials.html#autotoc_md220',1,'']]],
  ['advection–diffusion–reaction_14',['Example: combined advection–diffusion–reaction',['../finite-volume.html#autotoc_md28',1,'']]],
  ['advective_20flux_15',['Advective flux',['../finite-volume.html#autotoc_md26',1,'']]],
  ['advectivestress_16',['AdvectiveStress',['../syntax-models.html#advectivestress',1,'']]],
  ['against_20the_20synthetic_20data_17',['Calibrate the model against the synthetic data',['../python-examples-deterministic.html#autotoc_md183',1,'']]],
  ['analysis_18',['Code formatting and static analysis',['../tutorials-contributing.html#autotoc_md84',1,'']]],
  ['and_20design_20philosophy_19',['Features and design philosophy',['../index.html#autotoc_md4',1,'']]],
  ['and_20for_20our_20initial_20guess_20at_20the_20parameters_20',['and for our initial guess at the parameters',['../python-examples-deterministic.html#autotoc_md173',1,'Define the variability in the synthetic data and for our initial guess at the parameters'],['../python-examples-statistical.html#autotoc_md189',1,'Define the variability in the synthetic data and for our initial guess at the parameters']]],
  ['and_20forward_20operators_21',['Model structure and forward operators',['../tutorials-models-running-your-first-model.html#autotoc_md135',1,'']]],
  ['and_20inferred_20posteriors_22',['Compare priors, true posteriors, and inferred posteriors',['../python-examples-statistical.html#autotoc_md204',1,'']]],
  ['and_20regression_20tests_23',['Verification and regression tests',['../finite-volume.html#autotoc_md29',1,'']]],
  ['and_20sample_20our_20repeated_20case_24',['Go back and sample our repeated case',['../python-examples-statistical.html#autotoc_md203',1,'']]],
  ['and_20setting_20up_25',['and setting up',['../python-examples-crystal_plasticity-compare_formulations.html#autotoc_md155',1,'Importing required libraries and setting up'],['../python-examples-crystal_plasticity-polefigures.html#autotoc_md165',1,'Importing required libraries and setting up']]],
  ['and_20static_20analysis_26',['Code formatting and static analysis',['../tutorials-contributing.html#autotoc_md84',1,'']]],
  ['and_20their_20input_20file_20syntax_27',['and their input file syntax',['../syntax-data.html#autotoc_md56',1,'Available objects and their input file syntax'],['../syntax-drivers.html#autotoc_md57',1,'Available objects and their input file syntax'],['../syntax-equationsystems.html#autotoc_md58',1,'Available objects and their input file syntax'],['../syntax-models.html#autotoc_md59',1,'Available objects and their input file syntax'],['../syntax-schedulers.html#autotoc_md60',1,'Available objects and their input file syntax'],['../syntax-settings.html#autotoc_md61',1,'Available objects and their input file syntax'],['../syntax-solvers.html#autotoc_md62',1,'Available objects and their input file syntax'],['../syntax-tensors.html#autotoc_md63',1,'Available objects and their input file syntax']]],
  ['and_20training_20hyperparameters_28',['Setup a guide and training hyperparameters',['../python-examples-statistical.html#autotoc_md201',1,'']]],
  ['and_20tutorials_29',['Guides and Tutorials',['../tutorials.html',1,'']]],
  ['argument_20declaration_30',['Argument declaration',['../tutorials-extension-argument-declaration.html',1,'']]],
  ['arguments_31',['Command-line arguments',['../tutorials-contributing.html#autotoc_md80',1,'']]],
  ['arrheniusparameter_32',['ArrheniusParameter',['../syntax-models.html#arrheniusparameter',1,'']]],
  ['assembly_33',['Model assembly',['../system-models.html#model-assembly',1,'']]],
  ['associativeisotropicplastichardening_34',['AssociativeIsotropicPlasticHardening',['../syntax-models.html#associativeisotropicplastichardening',1,'']]],
  ['associativej2flowdirection_35',['AssociativeJ2FlowDirection',['../syntax-models.html#associativej2flowdirection',1,'']]],
  ['associativekinematicplastichardening_36',['AssociativeKinematicPlasticHardening',['../syntax-models.html#associativekinematicplastichardening',1,'']]],
  ['associativeplasticflow_37',['AssociativePlasticFlow',['../syntax-models.html#associativeplasticflow',1,'']]],
  ['at_20a_20fixed_20condition_38',['Now sample at run at a fixed condition',['../python-examples-statistical.html#autotoc_md196',1,'']]],
  ['at_20run_20at_20a_20fixed_20condition_39',['Now sample at run at a fixed condition',['../python-examples-statistical.html#autotoc_md196',1,'']]],
  ['at_20the_20parameters_40',['at the parameters',['../python-examples-deterministic.html#autotoc_md173',1,'Define the variability in the synthetic data and for our initial guess at the parameters'],['../python-examples-statistical.html#autotoc_md189',1,'Define the variability in the synthetic data and for our initial guess at the parameters']]],
  ['automatic_20chain_20rule_41',['Automatic chain rule',['../system-models.html#automatic-chain-rule',1,'']]],
  ['automatic_20dependency_20registration_42',['Automatic dependency registration',['../system-models.html#automatic-dependency-registration',1,'']]],
  ['automatic_20dependency_20resolution_43',['Automatic dependency resolution',['../system-models.html#automatic-dependency-resolution',1,'']]],
  ['automatic_20differentiation_44',['Automatic differentiation',['../tutorials-optimization-automatic-differentiation.html',1,'Automatic differentiation'],['../system-models.html#automatic-differentiation',1,'Automatic differentiation'],['../tutorials-optimization-automatic-differentiation.html#autotoc_md149',1,'Automatic differentiation']]],
  ['automatic_20input_20output_20identification_45',['Automatic input/output identification',['../system-models.html#automatic-input-output-identification',1,'']]],
  ['available_20models_46',['available models',['../tutorials-extension.html#autotoc_md93',1,'Seaching for available models'],['../tutorials-models-running-your-first-model.html#autotoc_md131',1,'Searching for available models']]],
  ['available_20objects_20and_20their_20input_20file_20syntax_47',['Available objects and their input file syntax',['../syntax-data.html#autotoc_md56',1,'Available objects and their input file syntax'],['../syntax-drivers.html#autotoc_md57',1,'Available objects and their input file syntax'],['../syntax-equationsystems.html#autotoc_md58',1,'Available objects and their input file syntax'],['../syntax-models.html#autotoc_md59',1,'Available objects and their input file syntax'],['../syntax-schedulers.html#autotoc_md60',1,'Available objects and their input file syntax'],['../syntax-settings.html#autotoc_md61',1,'Available objects and their input file syntax'],['../syntax-solvers.html#autotoc_md62',1,'Available objects and their input file syntax'],['../syntax-tensors.html#autotoc_md63',1,'Available objects and their input file syntax']]],
  ['avramierofeevnucleation_48',['AvramiErofeevNucleation',['../syntax-models.html#avramierofeevnucleation',1,'']]],
  ['axis_20labeling_49',['Axis labeling',['../system-models.html#axis-labeling',1,'']]],
  ['axis_20names_50',['Reserved axis names',['../tutorials-naming-conventions.html#autotoc_md145',1,'']]]
];
