var searchData=
[
  ['data_0',['Data',['../syntax-data.html',1,'[Data]'],['../system-data.html',1,'Data'],['../system-data.html#autotoc_md74',1,'Data']]],
  ['data_1',['data',['../python-examples-deterministic.html#autotoc_md192',1,'Calibrate the model against the synthetic data'],['../python-examples-deterministic.html#autotoc_md188',1,'Plot the synthetic data'],['../python-examples-statistical.html#autotoc_md204',1,'Plot the synthetic data'],['../python-examples-deterministic.html#autotoc_md187',1,'Run the model to generate the synthetic data'],['../python-examples-statistical.html#autotoc_md203',1,'Run the model to generate the synthetic data'],['../tutorials-tensors-tensor-view.html#autotoc_md226',1,'Who touched my data?']]],
  ['data_20and_20for_20our_20initial_20guess_20at_20the_20parameters_2',['data and for our initial guess at the parameters',['../python-examples-deterministic.html#autotoc_md182',1,'Define the variability in the synthetic data and for our initial guess at the parameters'],['../python-examples-statistical.html#autotoc_md198',1,'Define the variability in the synthetic data and for our initial guess at the parameters']]],
  ['data_20scarcity_3',['Challenge 2: Data scarcity',['../tutorials-optimization-pyzag.html#autotoc_md162',1,'']]],
  ['declaration_4',['declaration',['../tutorials-extension-argument-declaration.html',1,'Argument declaration'],['../tutorials-extension-argument-declaration.html#autotoc_md95',1,'Parameter declaration'],['../tutorials-extension-argument-declaration.html#autotoc_md94',1,'Variable declaration']]],
  ['defaults_20keys_20changed_5',['Settings defaults/keys changed',['../migration-200-210.html#autotoc_md22',1,'']]],
  ['define_20the_20variability_20in_20the_20synthetic_20data_20and_20for_20our_20initial_20guess_20at_20the_20parameters_6',['Define the variability in the synthetic data and for our initial guess at the parameters',['../python-examples-deterministic.html#autotoc_md182',1,'Define the variability in the synthetic data and for our initial guess at the parameters'],['../python-examples-statistical.html#autotoc_md198',1,'Define the variability in the synthetic data and for our initial guess at the parameters']]],
  ['defining_20the_20system_20of_20equations_7',['Defining the system of equations',['../tutorials-models-implicit-model.html#autotoc_md117',1,'']]],
  ['definition_8',['definition',['../system-models.html#model-definition',1,'Model definition'],['../tutorials-optimization-automatic-differentiation.html#autotoc_md157',1,'Model definition'],['../tutorials-extension-model-composition.html#autotoc_md104',1,'Problem definition'],['../tutorials-optimization-parameter-calibration.html#autotoc_md159',1,'Problem definition']]],
  ['deformation_9',['Simulate rolling deformation',['../python-examples-crystal_plasticity-polefigures.html#autotoc_md176',1,'']]],
  ['deformation_20for_20the_20seperated_20model_10',['Simulate rolling deformation for the seperated model',['../python-examples-crystal_plasticity-compare_formulations.html#autotoc_md166',1,'']]],
  ['degradation_20functions_11',['Degradation functions',['../phase-field-fracture.html#autotoc_md40',1,'']]],
  ['denselu_12',['DenseLU',['../syntax-solvers.html#denselu',1,'']]],
  ['density_13',['Strain Energy Density',['../phase-field-fracture.html#autotoc_md41',1,'']]],
  ['dependencies_14',['dependencies',['../dependency-management.html#autotoc_md9',1,'List of dependencies'],['../dependency-management.html#autotoc_md10',1,'Skipping dependencies']]],
  ['dependency_20management_15',['Dependency management',['../dependency-management.html',1,'']]],
  ['dependency_20registration_16',['Automatic dependency registration',['../system-models.html#automatic-dependency-registration',1,'']]],
  ['dependency_20resolution_17',['Automatic dependency resolution',['../system-models.html#automatic-dependency-resolution',1,'']]],
  ['dependency_20search_18',['Dependency search',['../dependency-management.html#autotoc_md8',1,'']]],
  ['derivatives_20of_20recursive_20nonlinear_20functions_19',['Challenge 1: Obtaining parameter derivatives of recursive nonlinear functions',['../tutorials-optimization-pyzag.html#autotoc_md161',1,'']]],
  ['description_20',['description',['../tutorials-extension.html#autotoc_md101',1,'Problem description'],['../tutorials-models-implicit-model.html#autotoc_md116',1,'Problem description'],['../tutorials-models-just-in-time-compilation.html#autotoc_md121',1,'Problem description'],['../tutorials-models-model-composition.html#autotoc_md126',1,'Problem description'],['../tutorials-models-model-parameters.html#autotoc_md130',1,'Problem description'],['../tutorials-models-model-parameters-revisited.html#autotoc_md134',1,'Problem description'],['../tutorials-models-running-your-first-model.html#autotoc_md139',1,'Problem description'],['../tutorials-models-transient-driver.html#autotoc_md146',1,'Problem description']]],
  ['design_20philosophy_21',['Features and design philosophy',['../index.html#autotoc_md3',1,'']]],
  ['details_22',['details',['../reactive-infiltration.html#autotoc_md45',1,'Implementation details'],['../thermosetting-pyrolysis.html#autotoc_md63',1,'Implementation details']]],
  ['deterministic_20material_20model_20calibration_23',['Deterministic material model calibration',['../python-examples-deterministic.html',1,'']]],
  ['development_24',['Model development',['../tutorials-contributing.html#autotoc_md88',1,'']]],
  ['device_25',['Device',['../tutorials-models-evaluation-device.html#autotoc_md113',1,'']]],
  ['device_26',['device',['../tutorials-models-evaluation-device.html#autotoc_md115',1,'Evaluating the model on a different device'],['../tutorials-models-evaluation-device.html',1,'Evaluation device'],['../tutorials-models-evaluation-device.html#autotoc_md114',1,'Specifying a device']]],
  ['differencemillerindex_27',['DifferenceMillerIndex',['../syntax-tensors.html#differencemillerindex',1,'']]],
  ['differencequaternion_28',['DifferenceQuaternion',['../syntax-tensors.html#differencequaternion',1,'']]],
  ['differencer2_29',['DifferenceR2',['../syntax-tensors.html#differencer2',1,'']]],
  ['differencer3_30',['DifferenceR3',['../syntax-tensors.html#differencer3',1,'']]],
  ['differencer4_31',['DifferenceR4',['../syntax-tensors.html#differencer4',1,'']]],
  ['differencerot_32',['DifferenceRot',['../syntax-tensors.html#differencerot',1,'']]],
  ['differencescalar_33',['DifferenceScalar',['../syntax-tensors.html#differencescalar',1,'']]],
  ['differencesffr4_34',['DifferenceSFFR4',['../syntax-tensors.html#differencesffr4',1,'']]],
  ['differencesfr3_35',['DifferenceSFR3',['../syntax-tensors.html#differencesfr3',1,'']]],
  ['differencesr2_36',['DifferenceSR2',['../syntax-tensors.html#differencesr2',1,'']]],
  ['differencessr4_37',['DifferenceSSR4',['../syntax-tensors.html#differencessr4',1,'']]],
  ['differenceswr4_38',['DifferenceSWR4',['../syntax-tensors.html#differenceswr4',1,'']]],
  ['differencetensor_39',['DifferenceTensor',['../syntax-tensors.html#differencetensor',1,'']]],
  ['differencevec_40',['DifferenceVec',['../syntax-tensors.html#differencevec',1,'']]],
  ['differencewffr4_41',['DifferenceWFFR4',['../syntax-tensors.html#differencewffr4',1,'']]],
  ['differencewr2_42',['DifferenceWR2',['../syntax-tensors.html#differencewr2',1,'']]],
  ['differencewsr4_43',['DifferenceWSR4',['../syntax-tensors.html#differencewsr4',1,'']]],
  ['differencewwr4_44',['DifferenceWWR4',['../syntax-tensors.html#differencewwr4',1,'']]],
  ['different_20device_45',['Evaluating the model on a different device',['../tutorials-models-evaluation-device.html#autotoc_md115',1,'']]],
  ['differentiation_46',['differentiation',['../tutorials-optimization-automatic-differentiation.html',1,'Automatic differentiation'],['../system-models.html#automatic-differentiation',1,'Automatic differentiation'],['../tutorials-optimization-automatic-differentiation.html#autotoc_md158',1,'Automatic differentiation']]],
  ['diffusionlimitedreaction_47',['DiffusionLimitedReaction',['../syntax-models.html#diffusionlimitedreaction',1,'']]],
  ['dimensional_20indexing_20tools_48',['Dimensional indexing tools',['../tutorials-tensors-indexing.html#autotoc_md219',1,'']]],
  ['directory_49',['Sub-directory',['../external-project-integration.html#autotoc_md16',1,'']]],
  ['discrete_20pole_20figure_50',['Plot a discrete pole figure',['../python-examples-crystal_plasticity-polefigures.html#autotoc_md177',1,'']]],
  ['discretization_51',['Finite volume discretization',['../finite-volume.html#autotoc_md32',1,'']]],
  ['dislocationobstaclestrengthmap_52',['DislocationObstacleStrengthMap',['../syntax-models.html#dislocationobstaclestrengthmap',1,'']]],
  ['dispatchers_53',['Work dispatchers',['../system-schedulers.html#autotoc_md80',1,'']]],
  ['documentation_54',['Documentation',['../tutorials-contributing.html#autotoc_md92',1,'']]],
  ['downstream_20c_20project_55',['Downstream C++ project',['../tutorials-getting-started.html#autotoc_md110',1,'']]],
  ['driver_56',['Driver',['../system-drivers.html',1,'']]],
  ['driver_57',['driver',['../python-examples-crystal_plasticity-polefigures.html#autotoc_md175',1,'pyzag driver'],['../tutorials-models-transient-driver.html',1,'Transient driver']]],
  ['driver_20for_20the_20integrated_20model_58',['pyzag driver for the integrated model',['../python-examples-crystal_plasticity-compare_formulations.html#autotoc_md168',1,'']]],
  ['driver_20for_20the_20separated_20model_59',['pyzag driver for the separated model',['../python-examples-crystal_plasticity-compare_formulations.html#autotoc_md165',1,'']]],
  ['drivers_60',['[Drivers]',['../syntax-drivers.html',1,'']]],
  ['drivers_61',['Optional scheduler hookup in drivers',['../migration-200-210.html#autotoc_md21',1,'']]],
  ['dynamically_20shaped_20tensor_62',['Dynamically shaped tensor',['../system-tensors.html#dynamically-shaped-tensor',1,'']]]
];
