var searchData=
[
  ['factory_0',['Factory',['../tutorials-extension-connection-to-input-files.html#autotoc_md91',1,'']]],
  ['factory_20methods_1',['Factory methods',['../tutorials-tensors-tensor-creation.html#autotoc_md212',1,'']]],
  ['features_20and_20design_20philosophy_2',['Features and design philosophy',['../index.html#autotoc_md4',1,'']]],
  ['fetchcontent_3',['FetchContent',['../external-project-integration.html#autotoc_md18',1,'']]],
  ['field_20fracture_4',['Phase-Field Fracture',['../phase-field-fracture.html',1,'']]],
  ['figure_5',['Plot a discrete pole figure',['../python-examples-crystal_plasticity-polefigures.html#autotoc_md168',1,'']]],
  ['figures_6',['Plot the pole figures',['../python-examples-crystal_plasticity-compare_formulations.html#autotoc_md163',1,'']]],
  ['file_7',['Example Input File',['../thermosetting-pyrolysis.html#autotoc_md55',1,'']]],
  ['file_8',['file',['../reactive-infiltration.html#autotoc_md37',1,'Complete input file'],['../tutorials-models-input-file.html',1,'Input file'],['../tutorials-extension-connection-to-input-files.html#autotoc_md89',1,'Input file'],['../tutorials-extension-model-composition.html#autotoc_md96',1,'Input file'],['../tutorials-models-running-your-first-model.html#autotoc_md134',1,'Loading a model from the input file'],['../tutorials-models-model-composition.html#autotoc_md118',1,'Writing the input file'],['../tutorials-models-running-your-first-model.html#autotoc_md132',1,'Writing the input file']]],
  ['file_20syntax_9',['file syntax',['../syntax-data.html#autotoc_md56',1,'Available objects and their input file syntax'],['../syntax-drivers.html#autotoc_md57',1,'Available objects and their input file syntax'],['../syntax-equationsystems.html#autotoc_md58',1,'Available objects and their input file syntax'],['../syntax-models.html#autotoc_md59',1,'Available objects and their input file syntax'],['../syntax-schedulers.html#autotoc_md60',1,'Available objects and their input file syntax'],['../syntax-settings.html#autotoc_md61',1,'Available objects and their input file syntax'],['../syntax-solvers.html#autotoc_md62',1,'Available objects and their input file syntax'],['../syntax-tensors.html#autotoc_md63',1,'Available objects and their input file syntax']]],
  ['files_10',['Connection to input files',['../tutorials-extension-connection-to-input-files.html',1,'']]],
  ['fillr2_11',['FillR2',['../syntax-tensors.html#fillr2',1,'']]],
  ['fillrot_12',['FillRot',['../syntax-tensors.html#fillrot',1,'']]],
  ['fillsr2_13',['FillSR2',['../syntax-tensors.html#fillsr2',1,'']]],
  ['fillwr2_14',['FillWR2',['../syntax-tensors.html#fillwr2',1,'']]],
  ['find_5fpackage_15',['find_package',['../external-project-integration.html#autotoc_md19',1,'']]],
  ['finite_20volume_20discretization_16',['Finite volume discretization',['../finite-volume.html#autotoc_md23',1,'']]],
  ['finite_20volume_20transport_20model_20building_20blocks_17',['Finite volume transport model building blocks',['../finite-volume.html#autotoc_md27',1,'']]],
  ['finite_20volume_20transport_20physics_18',['Finite Volume Transport Physics',['../finite-volume.html',1,'']]],
  ['finitevolumeappendboundarycondition_19',['FiniteVolumeAppendBoundaryCondition',['../syntax-models.html#finitevolumeappendboundarycondition',1,'']]],
  ['finitevolumegradient_20',['FiniteVolumeGradient',['../syntax-models.html#finitevolumegradient',1,'']]],
  ['finitevolumeupwindedadvectiveflux_21',['FiniteVolumeUpwindedAdvectiveFlux',['../syntax-models.html#finitevolumeupwindedadvectiveflux',1,'']]],
  ['first_20model_22',['Running your first model',['../tutorials-models-running-your-first-model.html',1,'']]],
  ['fischerburmeister_23',['FischerBurmeister',['../syntax-models.html#fischerburmeister',1,'']]],
  ['fixed_20condition_24',['Now sample at run at a fixed condition',['../python-examples-statistical.html#autotoc_md196',1,'']]],
  ['fixorientation_25',['FixOrientation',['../syntax-models.html#fixorientation',1,'']]],
  ['flow_20rules_26',['Flow rules',['../solid-mechanics.html#autotoc_md48',1,'']]],
  ['flux_27',['Advective flux',['../finite-volume.html#autotoc_md26',1,'']]],
  ['for_20available_20models_28',['for available models',['../tutorials-extension.html#autotoc_md93',1,'Seaching for available models'],['../tutorials-models-running-your-first-model.html#autotoc_md131',1,'Searching for available models']]],
  ['for_20loop_29',['For loop',['../tutorials-models-vectorization.html#autotoc_md141',1,'']]],
  ['for_20loop_20versus_20vectorization_3a_20a_20numerical_20experiment_30',['For loop versus vectorization: A numerical experiment',['../tutorials-models-vectorization.html#autotoc_md140',1,'']]],
  ['for_20our_20initial_20guess_20at_20the_20parameters_31',['for our initial guess at the parameters',['../python-examples-deterministic.html#autotoc_md173',1,'Define the variability in the synthetic data and for our initial guess at the parameters'],['../python-examples-statistical.html#autotoc_md189',1,'Define the variability in the synthetic data and for our initial guess at the parameters']]],
  ['for_20the_20integrated_20model_32',['pyzag driver for the integrated model',['../python-examples-crystal_plasticity-compare_formulations.html#autotoc_md159',1,'']]],
  ['for_20the_20multiplicative_20model_33',['for the multiplicative model',['../python-examples-crystal_plasticity-compare_formulations.html#autotoc_md161',1,'Extract the orientations for the multiplicative model'],['../python-examples-crystal_plasticity-compare_formulations.html#autotoc_md160',1,'Simulate for the multiplicative model']]],
  ['for_20the_20multiplicative_20model_20results_34',['Construct the ODF for the multiplicative model results',['../python-examples-crystal_plasticity-compare_formulations.html#autotoc_md162',1,'']]],
  ['for_20the_20repeated_20experiment_35',['Conditions for the repeated experiment',['../python-examples-statistical.html#autotoc_md188',1,'']]],
  ['for_20the_20separated_20model_36',['pyzag driver for the separated model',['../python-examples-crystal_plasticity-compare_formulations.html#autotoc_md156',1,'']]],
  ['for_20the_20seperated_20model_37',['for the seperated model',['../python-examples-crystal_plasticity-compare_formulations.html#autotoc_md158',1,'ODF reconstruction for the seperated model'],['../python-examples-crystal_plasticity-compare_formulations.html#autotoc_md157',1,'Simulate rolling deformation for the seperated model']]],
  ['for_20training_38',['for training',['../python-examples-deterministic.html#autotoc_md180',1,'Setup the model for training'],['../python-examples-statistical.html#autotoc_md197',1,'Setup the model for training']]],
  ['formatting_20and_20static_20analysis_39',['Code formatting and static analysis',['../tutorials-contributing.html#autotoc_md84',1,'']]],
  ['formulations_40',['Crystal plasticity formulations',['../python-examples-crystal_plasticity-compare_formulations.html',1,'']]],
  ['forward_20operator_41',['The forward operator',['../tutorials-extension-the-forward-operator.html',1,'']]],
  ['forward_20operators_42',['Model structure and forward operators',['../tutorials-models-running-your-first-model.html#autotoc_md135',1,'']]],
  ['fracture_43',['Phase-Field Fracture',['../phase-field-fracture.html',1,'']]],
  ['framework_44',['Framework',['../thermosetting-pyrolysis.html#autotoc_md51',1,'']]],
  ['fredrickarmstrongplastichardening_45',['FredrickArmstrongPlasticHardening',['../syntax-models.html#fredrickarmstrongplastichardening',1,'']]],
  ['from_20the_20input_20file_46',['Loading a model from the input file',['../tutorials-models-running-your-first-model.html#autotoc_md134',1,'']]],
  ['frontend_47',['Choosing the frontend',['../tutorials-models-running-your-first-model.html#autotoc_md133',1,'']]],
  ['fullmillerindex_48',['FullMillerIndex',['../syntax-tensors.html#fullmillerindex',1,'']]],
  ['fullquaternion_49',['FullQuaternion',['../syntax-tensors.html#fullquaternion',1,'']]],
  ['fullr2_50',['FullR2',['../syntax-tensors.html#fullr2',1,'']]],
  ['fullr3_51',['FullR3',['../syntax-tensors.html#fullr3',1,'']]],
  ['fullr4_52',['FullR4',['../syntax-tensors.html#fullr4',1,'']]],
  ['fullrot_53',['FullRot',['../syntax-tensors.html#fullrot',1,'']]],
  ['fullscalar_54',['FullScalar',['../syntax-tensors.html#fullscalar',1,'']]],
  ['fullsffr4_55',['FullSFFR4',['../syntax-tensors.html#fullsffr4',1,'']]],
  ['fullsfr3_56',['FullSFR3',['../syntax-tensors.html#fullsfr3',1,'']]],
  ['fullsr2_57',['FullSR2',['../syntax-tensors.html#fullsr2',1,'']]],
  ['fullssr4_58',['FullSSR4',['../syntax-tensors.html#fullssr4',1,'']]],
  ['fullswr4_59',['FullSWR4',['../syntax-tensors.html#fullswr4',1,'']]],
  ['fulltensor_60',['FullTensor',['../syntax-tensors.html#fulltensor',1,'']]],
  ['fullvec_61',['FullVec',['../syntax-tensors.html#fullvec',1,'']]],
  ['fullwffr4_62',['FullWFFR4',['../syntax-tensors.html#fullwffr4',1,'']]],
  ['fullwr2_63',['FullWR2',['../syntax-tensors.html#fullwr2',1,'']]],
  ['fullwsr4_64',['FullWSR4',['../syntax-tensors.html#fullwsr4',1,'']]],
  ['fullwwr4_65',['FullWWR4',['../syntax-tensors.html#fullwwr4',1,'']]],
  ['function_66',['Perfectly Plastic Yield function',['../solid-mechanics.html#autotoc_md43',1,'']]],
  ['function_20theorem_67',['Remarks on the implicit function theorem',['../tutorials-models-implicit-model.html#autotoc_md110',1,'']]],
  ['functions_68',['functions',['../tutorials-optimization-pyzag.html#autotoc_md152',1,'Challenge 1: Obtaining parameter derivatives of recursive nonlinear functions'],['../phase-field-fracture.html#autotoc_md30',1,'Crack geometric functions'],['../phase-field-fracture.html#autotoc_md31',1,'Degradation functions']]]
];
