var searchData=
[
  ['c_20backend_0',['C backend',['../install.html#autotoc_md12',1,'C++ backend'],['../tutorials-contributing.html#testing-cpp',1,'C++ backend']]],
  ['c_20project_1',['Downstream C++ project',['../tutorials-getting-started.html#autotoc_md110',1,'']]],
  ['calibrate_20the_20model_2',['Setup parameters related to &lt;em&gt;how&lt;/em&gt; we calibrate the model',['../python-examples-deterministic.html#autotoc_md180',1,'']]],
  ['calibrate_20the_20model_20against_20the_20synthetic_20data_3',['Calibrate the model against the synthetic data',['../python-examples-deterministic.html#autotoc_md192',1,'']]],
  ['calibrated_20model_20coefficients_4',['Print the calibrated model coefficients',['../python-examples-deterministic.html#autotoc_md194',1,'']]],
  ['calibrated_20model_20predictions_5',['Plot the calibrated model predictions',['../python-examples-deterministic.html#autotoc_md193',1,'']]],
  ['calibration_6',['Calibration',['../tutorials-optimization-parameter-calibration.html#autotoc_md160',1,'']]],
  ['calibration_7',['calibration',['../python-examples-deterministic.html',1,'Deterministic material model calibration'],['../tutorials-optimization-parameter-calibration.html',1,'Parameter calibration']]],
  ['case_8',['Go back and sample our repeated case',['../python-examples-statistical.html#autotoc_md212',1,'']]],
  ['catch_20tests_9',['Catch tests',['../tutorials-contributing.html#testing-catch-tests',1,'']]],
  ['cell_20edge_20interpolation_10',['Cell-edge interpolation',['../finite-volume.html#autotoc_md33',1,'']]],
  ['centermillerindex_11',['CenterMillerIndex',['../syntax-tensors.html#centermillerindex',1,'']]],
  ['centerquaternion_12',['CenterQuaternion',['../syntax-tensors.html#centerquaternion',1,'']]],
  ['centerr2_13',['CenterR2',['../syntax-tensors.html#centerr2',1,'']]],
  ['centerr3_14',['CenterR3',['../syntax-tensors.html#centerr3',1,'']]],
  ['centerr4_15',['CenterR4',['../syntax-tensors.html#centerr4',1,'']]],
  ['centerrot_16',['CenterRot',['../syntax-tensors.html#centerrot',1,'']]],
  ['centerscalar_17',['CenterScalar',['../syntax-tensors.html#centerscalar',1,'']]],
  ['centersffr4_18',['CenterSFFR4',['../syntax-tensors.html#centersffr4',1,'']]],
  ['centersfr3_19',['CenterSFR3',['../syntax-tensors.html#centersfr3',1,'']]],
  ['centersr2_20',['CenterSR2',['../syntax-tensors.html#centersr2',1,'']]],
  ['centerssr4_21',['CenterSSR4',['../syntax-tensors.html#centerssr4',1,'']]],
  ['centerswr4_22',['CenterSWR4',['../syntax-tensors.html#centerswr4',1,'']]],
  ['centertensor_23',['CenterTensor',['../syntax-tensors.html#centertensor',1,'']]],
  ['centervec_24',['CenterVec',['../syntax-tensors.html#centervec',1,'']]],
  ['centerwffr4_25',['CenterWFFR4',['../syntax-tensors.html#centerwffr4',1,'']]],
  ['centerwr2_26',['CenterWR2',['../syntax-tensors.html#centerwr2',1,'']]],
  ['centerwsr4_27',['CenterWSR4',['../syntax-tensors.html#centerwsr4',1,'']]],
  ['centerwwr4_28',['CenterWWR4',['../syntax-tensors.html#centerwwr4',1,'']]],
  ['chabocheplastichardening_29',['ChabochePlasticHardening',['../syntax-models.html#chabocheplastichardening',1,'']]],
  ['chain_20rule_30',['Automatic chain rule',['../system-models.html#automatic-chain-rule',1,'']]],
  ['challenge_201_3a_20obtaining_20parameter_20derivatives_20of_20recursive_20nonlinear_20functions_31',['Challenge 1: Obtaining parameter derivatives of recursive nonlinear functions',['../tutorials-optimization-pyzag.html#autotoc_md161',1,'']]],
  ['challenge_202_3a_20data_20scarcity_32',['Challenge 2: Data scarcity',['../tutorials-optimization-pyzag.html#autotoc_md162',1,'']]],
  ['challenge_203_3a_20uncertainty_20quantification_33',['Challenge 3: Uncertainty quantification',['../tutorials-optimization-pyzag.html#autotoc_md163',1,'']]],
  ['changed_34',['Settings defaults/keys changed',['../migration-200-210.html#autotoc_md22',1,'']]],
  ['changes_35',['changes',['../migration-200-210.html#autotoc_md23',1,'Binary utility changes'],['../migration-200-210.html#autotoc_md19',1,'Input file changes'],['../migration-200-210.html#autotoc_md24',1,'Installation and integration changes']]],
  ['chemical_20reactions_36',['Chemical Reactions',['../chemical-reactions.html',1,'']]],
  ['choosing_20the_20frontend_37',['Choosing the frontend',['../tutorials-models-running-your-first-model.html#autotoc_md142',1,'']]],
  ['citing_20neml2_38',['Citing NEML2',['../index.html#autotoc_md4',1,'']]],
  ['class_39',['Base class',['../system-equationsystems.html#autotoc_md75',1,'']]],
  ['cmake_20integration_40',['CMake integration',['../external-project-integration.html#autotoc_md15',1,'']]],
  ['code_20formatting_20and_20static_20analysis_41',['Code formatting and static analysis',['../tutorials-contributing.html#autotoc_md93',1,'']]],
  ['code_20naming_20conventions_42',['Source code naming conventions',['../tutorials-naming-conventions.html#autotoc_md156',1,'']]],
  ['coefficients_43',['Print the calibrated model coefficients',['../python-examples-deterministic.html#autotoc_md194',1,'']]],
  ['combined_20advection–diffusion–reaction_44',['Example: combined advection–diffusion–reaction',['../finite-volume.html#autotoc_md37',1,'']]],
  ['command_20line_20arguments_45',['Command-line arguments',['../tutorials-contributing.html#autotoc_md89',1,'']]],
  ['compare_20priors_20true_20posteriors_20and_20inferred_20posteriors_46',['Compare priors, true posteriors, and inferred posteriors',['../python-examples-statistical.html#autotoc_md213',1,'']]],
  ['compare_20to_20the_20repeated_20test_47',['Sample the prior model to compare to the repeated test',['../python-examples-statistical.html#autotoc_md209',1,'']]],
  ['comparisons_20of_20the_20elastic_20strains_48',['Plot some comparisons of the elastic strains',['../python-examples-crystal_plasticity-compare_formulations.html#autotoc_md173',1,'']]],
  ['compilation_49',['Just-in-time compilation',['../tutorials-models-just-in-time-compilation.html',1,'']]],
  ['complete_20input_20file_50',['Complete input file',['../reactive-infiltration.html#autotoc_md46',1,'']]],
  ['components_51',['Installation layout/components',['../migration-200-210.html#autotoc_md26',1,'']]],
  ['composedmodel_52',['ComposedModel',['../syntax-models.html#composedmodel',1,'']]],
  ['composition_53',['composition',['../tutorials-extension-model-composition.html',1,'Model composition'],['../tutorials-models-model-composition.html',1,'Model composition'],['../system-models.html#model-composition',1,'Model composition']]],
  ['computing_54',['Heterogeneous computing',['../system-schedulers.html#autotoc_md79',1,'']]],
  ['condition_55',['Now sample at run at a fixed condition',['../python-examples-statistical.html#autotoc_md205',1,'']]],
  ['conditions_56',['conditions',['../python-examples-deterministic.html#autotoc_md181',1,'Setup the synthetic experimental conditions'],['../python-examples-statistical.html#autotoc_md196',1,'Setup the synthetic experimental conditions']]],
  ['conditions_20for_20the_20repeated_20experiment_57',['Conditions for the repeated experiment',['../python-examples-statistical.html#autotoc_md197',1,'']]],
  ['configuration_58',['Build system and configuration',['../migration-200-210.html#autotoc_md25',1,'']]],
  ['configure_20options_59',['Configure options',['../build-customization.html#autotoc_md5',1,'']]],
  ['configure_20presets_60',['Configure presets',['../build-customization.html#autotoc_md6',1,'']]],
  ['connection_20to_20input_20files_61',['Connection to input files',['../tutorials-extension-connection-to-input-files.html',1,'']]],
  ['consistent_20plasticity_62',['Consistent plasticity',['../solid-mechanics.html#autotoc_md49',1,'']]],
  ['construct_20the_20odf_20for_20the_20multiplicative_20model_20results_63',['Construct the ODF for the multiplicative model results',['../python-examples-crystal_plasticity-compare_formulations.html#autotoc_md171',1,'']]],
  ['continuous_20polefigure_64',['Plot a continuous polefigure',['../python-examples-crystal_plasticity-polefigures.html#autotoc_md179',1,'']]],
  ['contractinggeometry_65',['ContractingGeometry',['../syntax-models.html#contractinggeometry',1,'']]],
  ['contributing_66',['Contributing',['../tutorials-contributing.html',1,'']]],
  ['control_67',['Mixed stress/strain control',['../solid-mechanics.html#autotoc_md58',1,'']]],
  ['control_20volume_68',['Control volume',['../thermosetting-pyrolysis.html#autotoc_md62',1,'']]],
  ['conventions_69',['Naming Conventions',['../tutorials-naming-conventions.html',1,'']]],
  ['conventions_70',['conventions',['../tutorials-naming-conventions.html#autotoc_md153',1,'Naming conventions'],['../tutorials-naming-conventions.html#autotoc_md156',1,'Source code naming conventions'],['../tutorials-naming-conventions.html#autotoc_md155',1,'Variable naming conventions']]],
  ['convert_20the_20model_20to_20a_20hierarchical_20statistical_20model_71',['Convert the model to a hierarchical statistical model',['../python-examples-statistical.html#autotoc_md208',1,'']]],
  ['copy_72',['View versus copy',['../tutorials-tensors-tensor-view.html#autotoc_md225',1,'']]],
  ['copymillerindex_73',['CopyMillerIndex',['../syntax-models.html#copymillerindex',1,'']]],
  ['copyquaternion_74',['CopyQuaternion',['../syntax-models.html#copyquaternion',1,'']]],
  ['copyr2_75',['CopyR2',['../syntax-models.html#copyr2',1,'']]],
  ['copyr3_76',['CopyR3',['../syntax-models.html#copyr3',1,'']]],
  ['copyr4_77',['CopyR4',['../syntax-models.html#copyr4',1,'']]],
  ['copyrot_78',['CopyRot',['../syntax-models.html#copyrot',1,'']]],
  ['copyscalar_79',['CopyScalar',['../syntax-models.html#copyscalar',1,'']]],
  ['copysffr4_80',['CopySFFR4',['../syntax-models.html#copysffr4',1,'']]],
  ['copysfr3_81',['CopySFR3',['../syntax-models.html#copysfr3',1,'']]],
  ['copysr2_82',['CopySR2',['../syntax-models.html#copysr2',1,'']]],
  ['copyssr4_83',['CopySSR4',['../syntax-models.html#copyssr4',1,'']]],
  ['copyswr4_84',['CopySWR4',['../syntax-models.html#copyswr4',1,'']]],
  ['copyvec_85',['CopyVec',['../syntax-models.html#copyvec',1,'']]],
  ['copywffr4_86',['CopyWFFR4',['../syntax-models.html#copywffr4',1,'']]],
  ['copywr2_87',['CopyWR2',['../syntax-models.html#copywr2',1,'']]],
  ['copywsr4_88',['CopyWSR4',['../syntax-models.html#copywsr4',1,'']]],
  ['copywwr4_89',['CopyWWR4',['../syntax-models.html#copywwr4',1,'']]],
  ['crack_20geometric_20functions_90',['Crack geometric functions',['../phase-field-fracture.html#autotoc_md39',1,'']]],
  ['crackgeometricfunctionat1_91',['CrackGeometricFunctionAT1',['../syntax-models.html#crackgeometricfunctionat1',1,'']]],
  ['crackgeometricfunctionat2_92',['CrackGeometricFunctionAT2',['../syntax-models.html#crackgeometricfunctionat2',1,'']]],
  ['create_20the_20input_20tendors_93',['Create the input tendors',['../python-examples-statistical.html#autotoc_md201',1,'']]],
  ['create_20the_20input_20tensors_94',['Create the input tensors',['../python-examples-deterministic.html#autotoc_md185',1,'']]],
  ['creation_95',['creation',['../tutorials-tensors-tensor-creation.html',1,'Tensor creation'],['../system-tensors.html#tensor-creation',1,'Tensor creation']]],
  ['crystal_20plasticity_96',['Crystal plasticity',['../solid-mechanics.html#autotoc_md59',1,'']]],
  ['crystal_20plasticity_20formulations_97',['Crystal plasticity formulations',['../python-examples-crystal_plasticity-compare_formulations.html',1,'']]],
  ['crystalgeometry_98',['CrystalGeometry',['../syntax-data.html#crystalgeometry',1,'']]],
  ['csvscalar_99',['CSVScalar',['../syntax-tensors.html#csvscalar',1,'']]],
  ['csvsr2_100',['CSVSR2',['../syntax-tensors.html#csvsr2',1,'']]],
  ['csvvec_101',['CSVVec',['../syntax-tensors.html#csvvec',1,'']]],
  ['cubiccrystal_102',['CubicCrystal',['../syntax-data.html#cubiccrystal',1,'']]],
  ['cubicelasticitytensor_103',['CubicElasticityTensor',['../syntax-models.html#cubicelasticitytensor',1,'']]],
  ['curve_104',['Simulating the stress-strain curve',['../tutorials-models-transient-driver.html#autotoc_md147',1,'']]],
  ['customization_105',['Build Customization',['../build-customization.html',1,'']]],
  ['cylindricalchannelgeometry_106',['CylindricalChannelGeometry',['../syntax-models.html#cylindricalchannelgeometry',1,'']]]
];
