var searchData=
[
  ['macroscale_0',['Plasticity (macroscale)',['../solid-mechanics.html#autotoc_md39',1,'']]],
  ['makefile_20integration_1',['Makefile integration',['../external-project-integration.html#autotoc_md15',1,'']]],
  ['management_2',['Dependency management',['../dependency-management.html',1,'']]],
  ['material_20model_20calibration_3',['Deterministic material model calibration',['../python-examples-deterministic.html',1,'']]],
  ['material_20model_20learning_4',['Statistical material model learning',['../python-examples-statistical.html',1,'']]],
  ['material_20model_20library_20version_202_5',['The New Engineering Material model Library, version 2',['../index.html#autotoc_md2',1,'']]],
  ['mechanics_6',['Solid Mechanics',['../solid-mechanics.html',1,'']]],
  ['mechanisms_7',['Reaction mechanisms',['../chemical-reactions.html#autotoc_md20',1,'']]],
  ['method_20signature_8',['Method signature',['../tutorials-extension-the-forward-operator.html#autotoc_md98',1,'']]],
  ['methods_9',['Factory methods',['../tutorials-tensors-tensor-creation.html#autotoc_md212',1,'']]],
  ['millerindex_10',['MillerIndex',['../syntax-tensors.html#millerindex',1,'']]],
  ['millerindexconstantparameter_11',['MillerIndexConstantParameter',['../syntax-models.html#millerindexconstantparameter',1,'']]],
  ['millerindexdynamicmean_12',['MillerIndexDynamicMean',['../syntax-models.html#millerindexdynamicmean',1,'']]],
  ['millerindexdynamicsum_13',['MillerIndexDynamicSum',['../syntax-models.html#millerindexdynamicsum',1,'']]],
  ['millerindexfromtorchscript_14',['MillerIndexFromTorchScript',['../syntax-tensors.html#millerindexfromtorchscript',1,'']]],
  ['millerindexinputparameter_15',['MillerIndexInputParameter',['../syntax-models.html#millerindexinputparameter',1,'']]],
  ['millerindexintermediatediff_16',['MillerIndexIntermediateDiff',['../syntax-models.html#millerindexintermediatediff',1,'']]],
  ['millerindexintermediatemean_17',['MillerIndexIntermediateMean',['../syntax-models.html#millerindexintermediatemean',1,'']]],
  ['millerindexintermediatesum_18',['MillerIndexIntermediateSum',['../syntax-models.html#millerindexintermediatesum',1,'']]],
  ['millerindexparametertostate_19',['MillerIndexParameterToState',['../syntax-models.html#millerindexparametertostate',1,'']]],
  ['mixed_20hardening_20',['Mixed hardening',['../solid-mechanics.html#autotoc_md47',1,'']]],
  ['mixed_20stress_20strain_20control_21',['Mixed stress/strain control',['../solid-mechanics.html#autotoc_md49',1,'']]],
  ['mixedcontrolsetup_22',['MixedControlSetup',['../syntax-models.html#mixedcontrolsetup',1,'']]],
  ['model_23',['Model',['../system-models.html',1,'']]],
  ['model_24',['model',['../python-examples-deterministic.html#autotoc_md175',1,'Actually setup the model'],['../python-examples-statistical.html#autotoc_md191',1,'Actually setup the model'],['../python-examples-statistical.html#autotoc_md199',1,'Convert the model to a hierarchical statistical model'],['../tutorials-models-running-your-first-model.html#autotoc_md136',1,'Evaluating the model'],['../python-examples-crystal_plasticity-compare_formulations.html#autotoc_md161',1,'Extract the orientations for the multiplicative model'],['../tutorials-models-implicit-model.html',1,'Implicit model'],['../python-examples-crystal_plasticity-compare_formulations.html#autotoc_md158',1,'ODF reconstruction for the seperated model'],['../python-examples-crystal_plasticity-compare_formulations.html#autotoc_md159',1,'pyzag driver for the integrated model'],['../python-examples-crystal_plasticity-compare_formulations.html#autotoc_md156',1,'pyzag driver for the separated model'],['../tutorials-models-running-your-first-model.html',1,'Running your first model'],['../python-examples-deterministic.html#autotoc_md171',1,'Setup parameters related to &lt;em&gt;how&lt;/em&gt; we calibrate the model'],['../python-examples-statistical.html#autotoc_md186',1,'Setup parameters related to &lt;em&gt;how&lt;/em&gt; we train the model'],['../python-examples-deterministic.html#autotoc_md174',1,'Setup the actual model'],['../python-examples-statistical.html#autotoc_md190',1,'Setup the actual model'],['../python-examples-crystal_plasticity-compare_formulations.html#autotoc_md160',1,'Simulate for the multiplicative model'],['../python-examples-crystal_plasticity-compare_formulations.html#autotoc_md157',1,'Simulate rolling deformation for the seperated model']]],
  ['model_20against_20the_20synthetic_20data_25',['Calibrate the model against the synthetic data',['../python-examples-deterministic.html#autotoc_md183',1,'']]],
  ['model_20assembly_26',['Model assembly',['../system-models.html#model-assembly',1,'']]],
  ['model_20based_20nonlinear_20system_27',['Model-based nonlinear system',['../system-equationsystems.html#autotoc_md69',1,'']]],
  ['model_20building_20blocks_28',['Finite volume transport model building blocks',['../finite-volume.html#autotoc_md27',1,'']]],
  ['model_20calibration_29',['Deterministic material model calibration',['../python-examples-deterministic.html',1,'']]],
  ['model_20coefficients_30',['Print the calibrated model coefficients',['../python-examples-deterministic.html#autotoc_md185',1,'']]],
  ['model_20composition_31',['Model composition',['../tutorials-extension-model-composition.html',1,'Model composition'],['../tutorials-models-model-composition.html',1,'Model composition'],['../system-models.html#model-composition',1,'Model composition']]],
  ['model_20definition_32',['Model definition',['../system-models.html#model-definition',1,'Model definition'],['../tutorials-optimization-automatic-differentiation.html#autotoc_md148',1,'Model definition']]],
  ['model_20development_33',['Model development',['../tutorials-contributing.html#autotoc_md79',1,'']]],
  ['model_20for_20training_34',['model for training',['../python-examples-deterministic.html#autotoc_md180',1,'Setup the model for training'],['../python-examples-statistical.html#autotoc_md197',1,'Setup the model for training']]],
  ['model_20from_20the_20input_20file_35',['Loading a model from the input file',['../tutorials-models-running-your-first-model.html#autotoc_md134',1,'']]],
  ['model_20inspection_36',['Model inspection',['../tutorials-extension-argument-declaration.html#autotoc_md87',1,'']]],
  ['model_20learning_37',['Statistical material model learning',['../python-examples-statistical.html',1,'']]],
  ['model_20library_20version_202_38',['The New Engineering Material model Library, version 2',['../index.html#autotoc_md2',1,'']]],
  ['model_20on_20a_20different_20device_39',['Evaluating the model on a different device',['../tutorials-models-evaluation-device.html#autotoc_md106',1,'']]],
  ['model_20parameters_40',['Model parameters',['../tutorials-models-model-parameters.html',1,'']]],
  ['model_20parameters_41',['model parameters',['../python-examples-deterministic.html#autotoc_md181',1,'Scale the model parameters'],['../python-examples-statistical.html#autotoc_md198',1,'Scale the model parameters']]],
  ['model_20parameters_20revisited_42',['Model parameters (revisited)',['../tutorials-models-model-parameters-revisited.html',1,'']]],
  ['model_20parameters_20with_20random_20values_43',['model parameters with random values',['../python-examples-deterministic.html#autotoc_md177',1,'Replace the model parameters with random values'],['../python-examples-statistical.html#autotoc_md193',1,'Replace the model parameters with random values']]],
  ['model_20predictions_44',['Plot the calibrated model predictions',['../python-examples-deterministic.html#autotoc_md184',1,'']]],
  ['model_20results_45',['Construct the ODF for the multiplicative model results',['../python-examples-crystal_plasticity-compare_formulations.html#autotoc_md162',1,'']]],
  ['model_20structure_46',['Model structure',['../tutorials-models-just-in-time-compilation.html#autotoc_md113',1,'']]],
  ['model_20structure_20and_20forward_20operators_47',['Model structure and forward operators',['../tutorials-models-running-your-first-model.html#autotoc_md135',1,'']]],
  ['model_20to_20a_20hierarchical_20statistical_20model_48',['Convert the model to a hierarchical statistical model',['../python-examples-statistical.html#autotoc_md199',1,'']]],
  ['model_20to_20compare_20to_20the_20repeated_20test_49',['Sample the prior model to compare to the repeated test',['../python-examples-statistical.html#autotoc_md200',1,'']]],
  ['model_20to_20generate_20the_20synthetic_20data_50',['model to generate the synthetic data',['../python-examples-deterministic.html#autotoc_md178',1,'Run the model to generate the synthetic data'],['../python-examples-statistical.html#autotoc_md194',1,'Run the model to generate the synthetic data']]],
  ['model_20with_20the_20initial_20parameter_20values_51',['Run the model with the initial parameter values',['../python-examples-deterministic.html#autotoc_md182',1,'']]],
  ['models_52',['Models',['../syntax-models.html',1,'[Models]'],['../tutorials-models.html',1,'Models']]],
  ['models_53',['models',['../tutorials-extension.html#autotoc_md93',1,'Seaching for available models'],['../tutorials-models-running-your-first-model.html#autotoc_md131',1,'Searching for available models']]],
  ['models_3a_20the_20easy_20way_54',['Evaluating the models: The easy way',['../tutorials-models-model-composition.html#autotoc_md120',1,'']]],
  ['models_3a_20the_20hard_20way_55',['Evaluating the models: The hard way',['../tutorials-models-model-composition.html#autotoc_md119',1,'']]],
  ['multicolumncsvscalar_56',['MultiColumnCSVScalar',['../syntax-tensors.html#multicolumncsvscalar',1,'']]],
  ['multiplicative_20model_57',['multiplicative model',['../python-examples-crystal_plasticity-compare_formulations.html#autotoc_md161',1,'Extract the orientations for the multiplicative model'],['../python-examples-crystal_plasticity-compare_formulations.html#autotoc_md160',1,'Simulate for the multiplicative model']]],
  ['multiplicative_20model_20results_58',['Construct the ODF for the multiplicative model results',['../python-examples-crystal_plasticity-compare_formulations.html#autotoc_md162',1,'']]],
  ['my_20data_59',['Who touched my data?',['../tutorials-tensors-tensor-view.html#autotoc_md217',1,'']]]
];
