var searchData=
[
  ['macroscale_0',['Plasticity (macroscale)',['../solid-mechanics.html#autotoc_md48',1,'']]],
  ['makefile_20integration_1',['Makefile integration',['../external-project-integration.html#autotoc_md14',1,'']]],
  ['management_2',['Dependency management',['../dependency-management.html',1,'']]],
  ['material_20model_20calibration_3',['Deterministic material model calibration',['../python-examples-deterministic.html',1,'']]],
  ['material_20model_20learning_4',['Statistical material model learning',['../python-examples-statistical.html',1,'']]],
  ['material_20model_20library_20version_202_5',['The New Engineering Material model Library, version 2',['../index.html#autotoc_md1',1,'']]],
  ['mechanics_6',['Solid Mechanics',['../solid-mechanics.html',1,'']]],
  ['mechanisms_7',['Reaction mechanisms',['../chemical-reactions.html#autotoc_md29',1,'']]],
  ['method_20signature_8',['Method signature',['../tutorials-extension-the-forward-operator.html#autotoc_md107',1,'']]],
  ['methods_9',['Factory methods',['../tutorials-tensors-tensor-creation.html#autotoc_md221',1,'']]],
  ['migrating_20from_20v2_200_200_20to_20v2_201_200_10',['Migrating from v2.0.0 to v2.1.0',['../migration-200-210.html',1,'']]],
  ['migration_20to_20equationsystems_20nonlinearsystem_11',['Migration to EquationSystems (&lt;span class=&quot;tt&quot;&gt;NonlinearSystem&lt;/span&gt;)',['../migration-200-210.html#eqsys',1,'']]],
  ['millerindex_12',['MillerIndex',['../syntax-tensors.html#millerindex',1,'']]],
  ['millerindexconstantparameter_13',['MillerIndexConstantParameter',['../syntax-models.html#millerindexconstantparameter',1,'']]],
  ['millerindexdynamicmean_14',['MillerIndexDynamicMean',['../syntax-models.html#millerindexdynamicmean',1,'']]],
  ['millerindexdynamicsum_15',['MillerIndexDynamicSum',['../syntax-models.html#millerindexdynamicsum',1,'']]],
  ['millerindexfromtorchscript_16',['MillerIndexFromTorchScript',['../syntax-tensors.html#millerindexfromtorchscript',1,'']]],
  ['millerindexinputparameter_17',['MillerIndexInputParameter',['../syntax-models.html#millerindexinputparameter',1,'']]],
  ['millerindexintermediatediff_18',['MillerIndexIntermediateDiff',['../syntax-models.html#millerindexintermediatediff',1,'']]],
  ['millerindexintermediatemean_19',['MillerIndexIntermediateMean',['../syntax-models.html#millerindexintermediatemean',1,'']]],
  ['millerindexintermediatesum_20',['MillerIndexIntermediateSum',['../syntax-models.html#millerindexintermediatesum',1,'']]],
  ['millerindexparametertostate_21',['MillerIndexParameterToState',['../syntax-models.html#millerindexparametertostate',1,'']]],
  ['mixed_20hardening_22',['Mixed hardening',['../solid-mechanics.html#autotoc_md56',1,'']]],
  ['mixed_20stress_20strain_20control_23',['Mixed stress/strain control',['../solid-mechanics.html#autotoc_md58',1,'']]],
  ['mixedcontrolsetup_24',['MixedControlSetup',['../syntax-models.html#mixedcontrolsetup',1,'']]],
  ['model_25',['Model',['../system-models.html',1,'']]],
  ['model_26',['model',['../python-examples-deterministic.html#autotoc_md184',1,'Actually setup the model'],['../python-examples-statistical.html#autotoc_md200',1,'Actually setup the model'],['../python-examples-statistical.html#autotoc_md208',1,'Convert the model to a hierarchical statistical model'],['../tutorials-models-running-your-first-model.html#autotoc_md145',1,'Evaluating the model'],['../python-examples-crystal_plasticity-compare_formulations.html#autotoc_md170',1,'Extract the orientations for the multiplicative model'],['../tutorials-models-implicit-model.html',1,'Implicit model'],['../python-examples-crystal_plasticity-compare_formulations.html#autotoc_md167',1,'ODF reconstruction for the seperated model'],['../python-examples-crystal_plasticity-compare_formulations.html#autotoc_md168',1,'pyzag driver for the integrated model'],['../python-examples-crystal_plasticity-compare_formulations.html#autotoc_md165',1,'pyzag driver for the separated model'],['../tutorials-models-running-your-first-model.html',1,'Running your first model'],['../python-examples-deterministic.html#autotoc_md180',1,'Setup parameters related to &lt;em&gt;how&lt;/em&gt; we calibrate the model'],['../python-examples-statistical.html#autotoc_md195',1,'Setup parameters related to &lt;em&gt;how&lt;/em&gt; we train the model'],['../python-examples-deterministic.html#autotoc_md183',1,'Setup the actual model'],['../python-examples-statistical.html#autotoc_md199',1,'Setup the actual model'],['../python-examples-crystal_plasticity-compare_formulations.html#autotoc_md169',1,'Simulate for the multiplicative model'],['../python-examples-crystal_plasticity-compare_formulations.html#autotoc_md166',1,'Simulate rolling deformation for the seperated model']]],
  ['model_20against_20the_20synthetic_20data_27',['Calibrate the model against the synthetic data',['../python-examples-deterministic.html#autotoc_md192',1,'']]],
  ['model_20assembly_28',['Model assembly',['../system-models.html#model-assembly',1,'']]],
  ['model_20based_20nonlinear_20system_29',['Model-based nonlinear system',['../system-equationsystems.html#autotoc_md78',1,'']]],
  ['model_20building_20blocks_30',['Finite volume transport model building blocks',['../finite-volume.html#autotoc_md36',1,'']]],
  ['model_20calibration_31',['Deterministic material model calibration',['../python-examples-deterministic.html',1,'']]],
  ['model_20coefficients_32',['Print the calibrated model coefficients',['../python-examples-deterministic.html#autotoc_md194',1,'']]],
  ['model_20composition_33',['Model composition',['../tutorials-extension-model-composition.html',1,'Model composition'],['../tutorials-models-model-composition.html',1,'Model composition'],['../system-models.html#model-composition',1,'Model composition']]],
  ['model_20definition_34',['Model definition',['../system-models.html#model-definition',1,'Model definition'],['../tutorials-optimization-automatic-differentiation.html#autotoc_md157',1,'Model definition']]],
  ['model_20development_35',['Model development',['../tutorials-contributing.html#autotoc_md88',1,'']]],
  ['model_20for_20training_36',['model for training',['../python-examples-deterministic.html#autotoc_md189',1,'Setup the model for training'],['../python-examples-statistical.html#autotoc_md206',1,'Setup the model for training']]],
  ['model_20from_20the_20input_20file_37',['Loading a model from the input file',['../tutorials-models-running-your-first-model.html#autotoc_md143',1,'']]],
  ['model_20inspection_38',['Model inspection',['../tutorials-extension-argument-declaration.html#autotoc_md96',1,'']]],
  ['model_20learning_39',['Statistical material model learning',['../python-examples-statistical.html',1,'']]],
  ['model_20library_20version_202_40',['The New Engineering Material model Library, version 2',['../index.html#autotoc_md1',1,'']]],
  ['model_20on_20a_20different_20device_41',['Evaluating the model on a different device',['../tutorials-models-evaluation-device.html#autotoc_md115',1,'']]],
  ['model_20parameters_42',['Model parameters',['../tutorials-models-model-parameters.html',1,'']]],
  ['model_20parameters_43',['model parameters',['../python-examples-deterministic.html#autotoc_md190',1,'Scale the model parameters'],['../python-examples-statistical.html#autotoc_md207',1,'Scale the model parameters']]],
  ['model_20parameters_20revisited_44',['Model parameters (revisited)',['../tutorials-models-model-parameters-revisited.html',1,'']]],
  ['model_20parameters_20with_20random_20values_45',['model parameters with random values',['../python-examples-deterministic.html#autotoc_md186',1,'Replace the model parameters with random values'],['../python-examples-statistical.html#autotoc_md202',1,'Replace the model parameters with random values']]],
  ['model_20predictions_46',['Plot the calibrated model predictions',['../python-examples-deterministic.html#autotoc_md193',1,'']]],
  ['model_20results_47',['Construct the ODF for the multiplicative model results',['../python-examples-crystal_plasticity-compare_formulations.html#autotoc_md171',1,'']]],
  ['model_20structure_48',['Model structure',['../tutorials-models-just-in-time-compilation.html#autotoc_md122',1,'']]],
  ['model_20structure_20and_20forward_20operators_49',['Model structure and forward operators',['../tutorials-models-running-your-first-model.html#autotoc_md144',1,'']]],
  ['model_20to_20a_20hierarchical_20statistical_20model_50',['Convert the model to a hierarchical statistical model',['../python-examples-statistical.html#autotoc_md208',1,'']]],
  ['model_20to_20compare_20to_20the_20repeated_20test_51',['Sample the prior model to compare to the repeated test',['../python-examples-statistical.html#autotoc_md209',1,'']]],
  ['model_20to_20generate_20the_20synthetic_20data_52',['model to generate the synthetic data',['../python-examples-deterministic.html#autotoc_md187',1,'Run the model to generate the synthetic data'],['../python-examples-statistical.html#autotoc_md203',1,'Run the model to generate the synthetic data']]],
  ['model_20with_20the_20initial_20parameter_20values_53',['Run the model with the initial parameter values',['../python-examples-deterministic.html#autotoc_md191',1,'']]],
  ['models_54',['Models',['../syntax-models.html',1,'[Models]'],['../tutorials-models.html',1,'Models']]],
  ['models_55',['models',['../tutorials-extension.html#autotoc_md102',1,'Seaching for available models'],['../tutorials-models-running-your-first-model.html#autotoc_md140',1,'Searching for available models']]],
  ['models_3a_20the_20easy_20way_56',['Evaluating the models: The easy way',['../tutorials-models-model-composition.html#autotoc_md129',1,'']]],
  ['models_3a_20the_20hard_20way_57',['Evaluating the models: The hard way',['../tutorials-models-model-composition.html#autotoc_md128',1,'']]],
  ['multicolumncsvscalar_58',['MultiColumnCSVScalar',['../syntax-tensors.html#multicolumncsvscalar',1,'']]],
  ['multiplicative_20model_59',['multiplicative model',['../python-examples-crystal_plasticity-compare_formulations.html#autotoc_md170',1,'Extract the orientations for the multiplicative model'],['../python-examples-crystal_plasticity-compare_formulations.html#autotoc_md169',1,'Simulate for the multiplicative model']]],
  ['multiplicative_20model_20results_60',['Construct the ODF for the multiplicative model results',['../python-examples-crystal_plasticity-compare_formulations.html#autotoc_md171',1,'']]],
  ['my_20data_61',['Who touched my data?',['../tutorials-tensors-tensor-view.html#autotoc_md226',1,'']]]
];
