var searchData=
[
  ['tendors_0',['Create the input tendors',['../python-examples-statistical.html#autotoc_md201',1,'']]],
  ['tensor_1',['Tensor',['../system-tensors.html',1,'Tensor'],['../syntax-tensors.html#tensor',1,'Tensor']]],
  ['tensor_2',['tensor',['../system-tensors.html#dynamically-shaped-tensor',1,'Dynamically shaped tensor'],['../tutorials-tensors-tensor-creation.html#autotoc_md220',1,'Wrapping a torch tensor']]],
  ['tensor_20broadcasting_3',['Tensor broadcasting',['../system-tensors.html#tensor-broadcasting',1,'']]],
  ['tensor_20creation_4',['Tensor creation',['../tutorials-tensors-tensor-creation.html',1,'Tensor creation'],['../system-tensors.html#tensor-creation',1,'Tensor creation']]],
  ['tensor_20indexing_5',['Tensor indexing',['../system-tensors.html#tensor-indexing',1,'']]],
  ['tensor_20name_6',['Tensor name',['../tutorials-models-model-parameters-revisited.html#autotoc_md137',1,'']]],
  ['tensor_20types_7',['Tensor types',['../tutorials-tensors-tensor-types.html',1,'Tensor types'],['../system-tensors.html#tensor-types',1,'Tensor types'],['../tutorials-tensors-tensor-types.html#autotoc_md224',1,'Tensor types']]],
  ['tensor_20view_8',['Tensor view',['../tutorials-tensors-tensor-view.html',1,'']]],
  ['tensors_9',['Tensors',['../syntax-tensors.html',1,'[Tensors]'],['../tutorials-tensors.html',1,'Tensors']]],
  ['tensors_10',['tensors',['../python-examples-deterministic.html#autotoc_md185',1,'Create the input tensors'],['../system-tensors.html#statically-shaped-tensor',1,'Statically shaped tensors'],['../system-tensors.html#working-with-tensors',1,'Working with tensors']]],
  ['test_11',['Sample the prior model to compare to the repeated test',['../python-examples-statistical.html#autotoc_md209',1,'']]],
  ['tests_12',['tests',['../tutorials-contributing.html#testing-catch-tests',1,'Catch tests'],['../tutorials-contributing.html#testing-regression-tests',1,'Regression tests'],['../tutorials-contributing.html#testing-unit-tests',1,'Unit tests'],['../finite-volume.html#autotoc_md38',1,'Verification and regression tests'],['../tutorials-contributing.html#testing-verification-tests',1,'Verification tests']]],
  ['the_20actual_20model_13',['the actual model',['../python-examples-deterministic.html#autotoc_md183',1,'Setup the actual model'],['../python-examples-statistical.html#autotoc_md199',1,'Setup the actual model']]],
  ['the_20calibrated_20model_20coefficients_14',['Print the calibrated model coefficients',['../python-examples-deterministic.html#autotoc_md194',1,'']]],
  ['the_20calibrated_20model_20predictions_15',['Plot the calibrated model predictions',['../python-examples-deterministic.html#autotoc_md193',1,'']]],
  ['the_20easy_20way_16',['Evaluating the models: The easy way',['../tutorials-models-model-composition.html#autotoc_md129',1,'']]],
  ['the_20elastic_20strains_17',['Plot some comparisons of the elastic strains',['../python-examples-crystal_plasticity-compare_formulations.html#autotoc_md173',1,'']]],
  ['the_20forward_20operator_18',['The forward operator',['../tutorials-extension-the-forward-operator.html',1,'']]],
  ['the_20frontend_19',['Choosing the frontend',['../tutorials-models-running-your-first-model.html#autotoc_md142',1,'']]],
  ['the_20hard_20way_20',['Evaluating the models: The hard way',['../tutorials-models-model-composition.html#autotoc_md128',1,'']]],
  ['the_20implicit_20function_20theorem_21',['Remarks on the implicit function theorem',['../tutorials-models-implicit-model.html#autotoc_md119',1,'']]],
  ['the_20initial_20parameter_20values_22',['Run the model with the initial parameter values',['../python-examples-deterministic.html#autotoc_md191',1,'']]],
  ['the_20input_20file_23',['the input file',['../tutorials-models-running-your-first-model.html#autotoc_md143',1,'Loading a model from the input file'],['../tutorials-models-model-composition.html#autotoc_md127',1,'Writing the input file'],['../tutorials-models-running-your-first-model.html#autotoc_md141',1,'Writing the input file']]],
  ['the_20input_20tendors_24',['Create the input tendors',['../python-examples-statistical.html#autotoc_md201',1,'']]],
  ['the_20input_20tensors_25',['Create the input tensors',['../python-examples-deterministic.html#autotoc_md185',1,'']]],
  ['the_20integrated_20model_26',['pyzag driver for the integrated model',['../python-examples-crystal_plasticity-compare_formulations.html#autotoc_md168',1,'']]],
  ['the_20model_27',['the model',['../python-examples-deterministic.html#autotoc_md184',1,'Actually setup the model'],['../python-examples-statistical.html#autotoc_md200',1,'Actually setup the model'],['../tutorials-models-running-your-first-model.html#autotoc_md145',1,'Evaluating the model'],['../python-examples-deterministic.html#autotoc_md180',1,'Setup parameters related to &lt;em&gt;how&lt;/em&gt; we calibrate the model'],['../python-examples-statistical.html#autotoc_md195',1,'Setup parameters related to &lt;em&gt;how&lt;/em&gt; we train the model']]],
  ['the_20model_20against_20the_20synthetic_20data_28',['Calibrate the model against the synthetic data',['../python-examples-deterministic.html#autotoc_md192',1,'']]],
  ['the_20model_20for_20training_29',['the model for training',['../python-examples-deterministic.html#autotoc_md189',1,'Setup the model for training'],['../python-examples-statistical.html#autotoc_md206',1,'Setup the model for training']]],
  ['the_20model_20on_20a_20different_20device_30',['Evaluating the model on a different device',['../tutorials-models-evaluation-device.html#autotoc_md115',1,'']]],
  ['the_20model_20parameters_31',['the model parameters',['../python-examples-deterministic.html#autotoc_md190',1,'Scale the model parameters'],['../python-examples-statistical.html#autotoc_md207',1,'Scale the model parameters']]],
  ['the_20model_20parameters_20with_20random_20values_32',['the model parameters with random values',['../python-examples-deterministic.html#autotoc_md186',1,'Replace the model parameters with random values'],['../python-examples-statistical.html#autotoc_md202',1,'Replace the model parameters with random values']]],
  ['the_20model_20to_20a_20hierarchical_20statistical_20model_33',['Convert the model to a hierarchical statistical model',['../python-examples-statistical.html#autotoc_md208',1,'']]],
  ['the_20model_20to_20generate_20the_20synthetic_20data_34',['the model to generate the synthetic data',['../python-examples-deterministic.html#autotoc_md187',1,'Run the model to generate the synthetic data'],['../python-examples-statistical.html#autotoc_md203',1,'Run the model to generate the synthetic data']]],
  ['the_20model_20with_20the_20initial_20parameter_20values_35',['Run the model with the initial parameter values',['../python-examples-deterministic.html#autotoc_md191',1,'']]],
  ['the_20models_3a_20the_20easy_20way_36',['Evaluating the models: The easy way',['../tutorials-models-model-composition.html#autotoc_md129',1,'']]],
  ['the_20models_3a_20the_20hard_20way_37',['Evaluating the models: The hard way',['../tutorials-models-model-composition.html#autotoc_md128',1,'']]],
  ['the_20multiplicative_20model_38',['the multiplicative model',['../python-examples-crystal_plasticity-compare_formulations.html#autotoc_md170',1,'Extract the orientations for the multiplicative model'],['../python-examples-crystal_plasticity-compare_formulations.html#autotoc_md169',1,'Simulate for the multiplicative model']]],
  ['the_20multiplicative_20model_20results_39',['Construct the ODF for the multiplicative model results',['../python-examples-crystal_plasticity-compare_formulations.html#autotoc_md171',1,'']]],
  ['the_20new_20engineering_20material_20model_20library_20version_202_40',['The New Engineering Material model Library, version 2',['../index.html#autotoc_md1',1,'']]],
  ['the_20odf_20for_20the_20multiplicative_20model_20results_41',['Construct the ODF for the multiplicative model results',['../python-examples-crystal_plasticity-compare_formulations.html#autotoc_md171',1,'']]],
  ['the_20orientations_20for_20the_20multiplicative_20model_42',['Extract the orientations for the multiplicative model',['../python-examples-crystal_plasticity-compare_formulations.html#autotoc_md170',1,'']]],
  ['the_20parameter_20value_43',['the parameter value',['../tutorials-models-model-parameters.html#autotoc_md132',1,'Retrieving the parameter value'],['../tutorials-models-model-parameters.html#autotoc_md133',1,'Updating the parameter value']]],
  ['the_20parameters_44',['the parameters',['../python-examples-deterministic.html#autotoc_md182',1,'Define the variability in the synthetic data and for our initial guess at the parameters'],['../python-examples-statistical.html#autotoc_md198',1,'Define the variability in the synthetic data and for our initial guess at the parameters']]],
  ['the_20pole_20figures_45',['Plot the pole figures',['../python-examples-crystal_plasticity-compare_formulations.html#autotoc_md172',1,'']]],
  ['the_20prior_20model_20to_20compare_20to_20the_20repeated_20test_46',['Sample the prior model to compare to the repeated test',['../python-examples-statistical.html#autotoc_md209',1,'']]],
  ['the_20projectiles_47',['Lauching the projectiles',['../tutorials-extension-model-composition.html#autotoc_md106',1,'']]],
  ['the_20repeated_20experiment_48',['Conditions for the repeated experiment',['../python-examples-statistical.html#autotoc_md197',1,'']]],
  ['the_20repeated_20test_49',['Sample the prior model to compare to the repeated test',['../python-examples-statistical.html#autotoc_md209',1,'']]],
  ['the_20separated_20model_50',['pyzag driver for the separated model',['../python-examples-crystal_plasticity-compare_formulations.html#autotoc_md165',1,'']]],
  ['the_20seperated_20model_51',['the seperated model',['../python-examples-crystal_plasticity-compare_formulations.html#autotoc_md167',1,'ODF reconstruction for the seperated model'],['../python-examples-crystal_plasticity-compare_formulations.html#autotoc_md166',1,'Simulate rolling deformation for the seperated model']]],
  ['the_20stress_20strain_20curve_52',['Simulating the stress-strain curve',['../tutorials-models-transient-driver.html#autotoc_md147',1,'']]],
  ['the_20synthetic_20data_53',['the synthetic data',['../python-examples-deterministic.html#autotoc_md192',1,'Calibrate the model against the synthetic data'],['../python-examples-deterministic.html#autotoc_md188',1,'Plot the synthetic data'],['../python-examples-statistical.html#autotoc_md204',1,'Plot the synthetic data'],['../python-examples-deterministic.html#autotoc_md187',1,'Run the model to generate the synthetic data'],['../python-examples-statistical.html#autotoc_md203',1,'Run the model to generate the synthetic data']]],
  ['the_20synthetic_20data_20and_20for_20our_20initial_20guess_20at_20the_20parameters_54',['the synthetic data and for our initial guess at the parameters',['../python-examples-deterministic.html#autotoc_md182',1,'Define the variability in the synthetic data and for our initial guess at the parameters'],['../python-examples-statistical.html#autotoc_md198',1,'Define the variability in the synthetic data and for our initial guess at the parameters']]],
  ['the_20synthetic_20experimental_20conditions_55',['the synthetic experimental conditions',['../python-examples-deterministic.html#autotoc_md181',1,'Setup the synthetic experimental conditions'],['../python-examples-statistical.html#autotoc_md196',1,'Setup the synthetic experimental conditions']]],
  ['the_20system_20of_20equations_56',['the system of equations',['../tutorials-models-implicit-model.html#autotoc_md117',1,'Defining the system of equations'],['../tutorials-models-implicit-model.html#autotoc_md118',1,'Solving the system of equations']]],
  ['the_20training_20loop_57',['Run the training loop',['../python-examples-statistical.html#autotoc_md211',1,'']]],
  ['the_20variability_20in_20the_20synthetic_20data_20and_20for_20our_20initial_20guess_20at_20the_20parameters_58',['the variability in the synthetic data and for our initial guess at the parameters',['../python-examples-deterministic.html#autotoc_md182',1,'Define the variability in the synthetic data and for our initial guess at the parameters'],['../python-examples-statistical.html#autotoc_md198',1,'Define the variability in the synthetic data and for our initial guess at the parameters']]],
  ['their_20input_20file_20syntax_59',['their input file syntax',['../syntax-data.html#autotoc_md65',1,'Available objects and their input file syntax'],['../syntax-drivers.html#autotoc_md66',1,'Available objects and their input file syntax'],['../syntax-equationsystems.html#autotoc_md67',1,'Available objects and their input file syntax'],['../syntax-models.html#autotoc_md68',1,'Available objects and their input file syntax'],['../syntax-schedulers.html#autotoc_md69',1,'Available objects and their input file syntax'],['../syntax-settings.html#autotoc_md70',1,'Available objects and their input file syntax'],['../syntax-solvers.html#autotoc_md71',1,'Available objects and their input file syntax'],['../syntax-tensors.html#autotoc_md72',1,'Available objects and their input file syntax']]],
  ['theorem_60',['Remarks on the implicit function theorem',['../tutorials-models-implicit-model.html#autotoc_md119',1,'']]],
  ['thermaldeformationjacobian_61',['ThermalDeformationJacobian',['../syntax-models.html#thermaldeformationjacobian',1,'']]],
  ['thermaleigenstrain_62',['ThermalEigenstrain',['../syntax-models.html#thermaleigenstrain',1,'']]],
  ['thermosetting_20pyrolysis_63',['Thermosetting Pyrolysis',['../thermosetting-pyrolysis.html',1,'']]],
  ['time_20compilation_64',['Just-in-time compilation',['../tutorials-models-just-in-time-compilation.html',1,'']]],
  ['to_20a_20hierarchical_20statistical_20model_65',['Convert the model to a hierarchical statistical model',['../python-examples-statistical.html#autotoc_md208',1,'']]],
  ['to_20compare_20to_20the_20repeated_20test_66',['Sample the prior model to compare to the repeated test',['../python-examples-statistical.html#autotoc_md209',1,'']]],
  ['to_20equationsystems_20nonlinearsystem_67',['Migration to EquationSystems (&lt;span class=&quot;tt&quot;&gt;NonlinearSystem&lt;/span&gt;)',['../migration-200-210.html#eqsys',1,'']]],
  ['to_20generate_20the_20synthetic_20data_68',['to generate the synthetic data',['../python-examples-deterministic.html#autotoc_md187',1,'Run the model to generate the synthetic data'],['../python-examples-statistical.html#autotoc_md203',1,'Run the model to generate the synthetic data']]],
  ['to_20how_20we_20calibrate_20the_20model_69',['Setup parameters related to &lt;em&gt;how&lt;/em&gt; we calibrate the model',['../python-examples-deterministic.html#autotoc_md180',1,'']]],
  ['to_20how_20we_20train_20the_20model_70',['Setup parameters related to &lt;em&gt;how&lt;/em&gt; we train the model',['../python-examples-statistical.html#autotoc_md195',1,'']]],
  ['to_20input_20files_71',['Connection to input files',['../tutorials-extension-connection-to-input-files.html',1,'']]],
  ['to_20the_20repeated_20test_72',['Sample the prior model to compare to the repeated test',['../python-examples-statistical.html#autotoc_md209',1,'']]],
  ['to_20v2_201_200_73',['Migrating from v2.0.0 to v2.1.0',['../migration-200-210.html',1,'']]],
  ['tools_74',['Dimensional indexing tools',['../tutorials-tensors-indexing.html#autotoc_md219',1,'']]],
  ['top_20level_20sections_75',['New top-level sections',['../migration-200-210.html#autotoc_md20',1,'']]],
  ['torch_20tensor_76',['Wrapping a torch tensor',['../tutorials-tensors-tensor-creation.html#autotoc_md220',1,'']]],
  ['touched_20my_20data_77',['Who touched my data?',['../tutorials-tensors-tensor-view.html#autotoc_md226',1,'']]],
  ['tracing_78',['Tracing',['../tutorials-models-just-in-time-compilation.html#autotoc_md123',1,'']]],
  ['tracing_79',['Event tracing',['../system-schedulers.html#autotoc_md85',1,'']]],
  ['train_20the_20model_80',['Setup parameters related to &lt;em&gt;how&lt;/em&gt; we train the model',['../python-examples-statistical.html#autotoc_md195',1,'']]],
  ['training_81',['training',['../python-examples-deterministic.html#autotoc_md189',1,'Setup the model for training'],['../python-examples-statistical.html#autotoc_md206',1,'Setup the model for training']]],
  ['training_20hyperparameters_82',['Setup a guide and training hyperparameters',['../python-examples-statistical.html#autotoc_md210',1,'']]],
  ['training_20loop_83',['Run the training loop',['../python-examples-statistical.html#autotoc_md211',1,'']]],
  ['transient_20driver_84',['Transient driver',['../tutorials-models-transient-driver.html',1,'']]],
  ['transientdriver_85',['TransientDriver',['../syntax-drivers.html#transientdriver',1,'']]],
  ['transport_20model_20building_20blocks_86',['Finite volume transport model building blocks',['../finite-volume.html#autotoc_md36',1,'']]],
  ['true_20posteriors_20and_20inferred_20posteriors_87',['Compare priors, true posteriors, and inferred posteriors',['../python-examples-statistical.html#autotoc_md213',1,'']]],
  ['tutorials_88',['Guides and Tutorials',['../tutorials.html',1,'']]],
  ['tutorials_89',['tutorials',['../tutorials.html#autotoc_md229',1,'Advanced tutorials'],['../tutorials.html#autotoc_md228',1,'Basic tutorials']]],
  ['types_90',['types',['../tutorials-tensors-tensor-types.html',1,'Tensor types'],['../system-tensors.html#tensor-types',1,'Tensor types'],['../tutorials-tensors-tensor-types.html#autotoc_md224',1,'Tensor types']]]
];
