# Verification of CamanhoDavilaTraction against the closed-form bilinear
# damage law under a monotonic mixed-mode opening ramp with the BK propagation criterion.
# The reference time history (jumps and tractions) is generated by reference.py and stored
# in reference.csv. Under monotonic loading the irreversibility cap d = max(d_trial, d_old)
# is satisfied by d_trial alone, so the analytical formula matches the model output
# step-for-step.

[Tensors]
  [times]
    type = CSVScalar
    csv_file = 'reference.csv'
    column_names = 'time'
  []
  [jumps]
    type = CSVVec
    csv_file = 'reference.csv'
    column_names = 'delta_n delta_s1 delta_s2'
  []
  [tractions_ref]
    type = CSVVec
    csv_file = 'reference.csv'
    column_names = 'T_n T_s1 T_s2'
  []
[]

[Drivers]
  [driver]
    type = TransientDriver
    model = 'model'
    prescribed_time = 'times'
    force_Vec_names = 'displacement_jump'
    force_Vec_values = 'jumps'
    save_as = 'result.pt'
  []
  [verification]
    type = VTestVerification
    driver = 'driver'
    Vec_names = 'output.traction'
    Vec_values = 'tractions_ref'
    rtol = 1e-10
    # Bumped from 1e-12: the model and the analytical reference perform the
    # same arithmetic in different orders (tensor ops vs numpy scalar ops),
    # so fused-multiply-add reordering produces ~2e-12 ULP-level noise on
    # tractions of O(1e-2). Still ~10x tighter than rtol on the magnitudes
    # that matter.
    atol = 1e-11
  []
[]

[Models]
  [model]
    type = CamanhoDavilaTraction
    penalty_stiffness = 1000.0
    normal_fracture_toughness = 1.0
    shear_fracture_toughness = 2.0
    normal_strength = 10.0
    shear_strength = 15.0
    eta = 2.0
  []
[]
