# Verification of ExpTractionSeparation against the closed-form exponential damage law
# under a monotonic mixed-mode opening ramp. The reference time history (jumps and
# tractions) is generated by reference.py and stored in reference.csv. Under monotonic
# loading the irreversible-damage history collapses to the current effective separation,
# so the model output matches the analytical formula exactly.

[Tensors]
  [times]
    type = CSVScalar
    csv_file = 'reference.csv'
    column_names = 'time'
  []
  [jumps]
    type = CSVVec
    csv_file = 'reference.csv'
    column_names = 'delta_n delta_s1 delta_s2'
  []
  [tractions_ref]
    type = CSVVec
    csv_file = 'reference.csv'
    column_names = 'T_n T_s1 T_s2'
  []
[]

[Drivers]
  [driver]
    type = TransientDriver
    model = 'model'
    prescribed_time = 'times'
    force_Vec_names = 'displacement_jump'
    force_Vec_values = 'jumps'
    save_as = 'result.pt'
  []
  [verification]
    type = VTestVerification
    driver = 'driver'
    Vec_names = 'output.traction'
    Vec_values = 'tractions_ref'
    # Damage is path-dependent in general but path-independent for a monotonic ramp
    # (kappa = delta_eff at every step). The model evaluates the closed form in one shot,
    # so tight tolerances catch any sign / factor / wiring regression.
    rtol = 1e-10
    atol = 1e-12
  []
[]

[Models]
  [model]
    type = ExpTractionSeparation
    fracture_energy = 2.0
    characteristic_length = 1.0
    tangential_weight = 1.0
    regularizer = 1e-12
    irreversible_damage = true
  []
[]
