# Verification of PureElasticTractionSeparation against the closed-form linear-elastic
# response T = diag(K_n, K_t, K_t) * delta. The reference time history (jumps and
# tractions) is generated by reference.py and stored in reference.csv. The driver feeds
# the prescribed jumps to the model and verifies that output.traction matches the
# analytical reference at every time step.

[Tensors]
  [times]
    type = CSVScalar
    csv_file = 'reference.csv'
    column_names = 'time'
  []
  [jumps]
    type = CSVVec
    csv_file = 'reference.csv'
    column_names = 'delta_n delta_s1 delta_s2'
  []
  [tractions_ref]
    type = CSVVec
    csv_file = 'reference.csv'
    column_names = 'T_n T_s1 T_s2'
  []
[]

[Drivers]
  [driver]
    type = TransientDriver
    model = 'model'
    prescribed_time = 'times'
    force_Vec_names = 'displacement_jump'
    force_Vec_values = 'jumps'
    save_as = 'result.pt'
  []
  [verification]
    type = VTestVerification
    driver = 'driver'
    Vec_names = 'output.traction'
    Vec_values = 'tractions_ref'
    # Pure-elastic response has no integration error -- the model evaluates the closed form
    # in one shot and the reference is the same closed form. Tight tolerances catch any
    # arithmetic / wiring regression.
    rtol = 1e-10
    atol = 1e-12
  []
[]

[Models]
  [model]
    type = PureElasticTractionSeparation
    normal_stiffness = 1000.0
    tangential_stiffness = 500.0
  []
[]
