# neml2
# Verification of SalehaniIrani3DCTractionSeparation against the closed-form 3D exponential
# cohesive law. The reference time history (jumps and tractions) is generated by reference.py
# and stored in reference.csv. The driver feeds the prescribed jumps to the model and
# verifies that output.traction matches the analytical reference at every time step.

[Tensors]
  [times]
    type = CSVScalar
    csv_file = 'reference.csv'
    column_names = 'time'
  []
  [jumps]
    type = CSVVec
    csv_file = 'reference.csv'
    column_names = 'delta_n delta_s1 delta_s2'
  []
  [tractions_ref]
    type = CSVVec
    csv_file = 'reference.csv'
    column_names = 'T_n T_s1 T_s2'
  []
[]

[Drivers]
  [driver]
    type = TransientDriver
    model = 'model'
    prescribed_time = 'times'
    force_Vec_names = 'separation'
    force_Vec_values = 'jumps'
    save_as = 'result.pt'
  []
  [verification]
    type = VTestVerification
    driver = 'driver'
    Vec_names = 'output.traction'
    Vec_values = 'tractions_ref'
    # No internal state and no implicit solve -- the model evaluates the analytical exponential
    # cohesive law in one shot. Tight tolerances catch any sign / factor / wiring regression.
    rtol = 1e-10
    atol = 1e-12
  []
[]

[Models]
  [decompose]
    type = VecComponents
    from = 'separation'
    to = 'normal_separation tangential_separation_1 tangential_separation_2'
  []
  [traction]
    type = SalehaniIraniTraction
    normal_characteristic_length = 1.0
    tangential_characteristic_length = 1.0
    normal_strength = 1.0
    shear_strength = 1.0
  []
  [model]
    type = ComposedModel
    models = 'decompose traction'
  []
[]
