name: Documentation

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  pull_request_target:
    branches: [main]
    types:
      - opened
      - reopened
      - synchronize
      - closed # This is important for the ghpage preview to clean up after itself

# Newer commits should cancel old runs
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    if: github.event_name == 'push' || github.ref_name != 'main'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      # - uses: actions/setup-python@v5
      #   with:
      #     python-version: "3.8"
      # - name: Install dependencies
      #   run: |
      #     sudo apt install graphviz
      #     pip install -r requirements.txt
      #     pip install torch==2.2.2
      # - name: Configure documentation
      #   run: |
      #     cmake \
      #       -DCMAKE_BUILD_TYPE=Release \
      #       -DCMAKE_UNITY_BUILD=ON \
      #       -DNEML2_TESTS=OFF \
      #       -DNEML2_RUNNER=OFF \
      #       -DNEML2_PYBIND=ON \
      #       -DNEML2_DOC=ON \
      #       -B build \
      #       .
      # - name: Build documentation
      #   run: cmake --build build --target html -j 2 --
      # - name: Show build logs for C++ documentation
      #   run: cat build/doc/doxygen.html.log
      # - name: Show build logs for Python documentation
      #   run: cat build/doc/doxygen.python.log
      # - name: Show objects with missing documentation
      #   run: cat build/doc/syntax_error.log
      # - name: Error if syntax errors were detected
      #   run: grep -q "No syntax error" build/doc/syntax_error.log
      - name: Fake documentation
        run: |
          mkdir -p build/doc/build/html
          touch build/doc/build/html/index.html
      - name: Upload documentation
        uses: actions/upload-artifact@v4
        with:
          name: doc
          path: build/doc/build/html
  preview:
    needs: build
    if: github.event_name == 'pull_request' && github.ref_name == 'main'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Download documentation
        uses: actions/download-artifact@v4
        with:
          name: doc
          path: html
      - name: Preview GitHub Pages
        uses: rossjrw/pr-preview-action@v1
        with:
          source-dir: html
  deploy:
    needs: build
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Download documentation
        uses: actions/download-artifact@v4
        with:
          name: doc
          path: html
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4.4.1
        with:
          branch: gh-pages
          folder: html
          clean-exclude: pr-preview/
          force: false
