name: Documentation

on:
  push:
    branches: [main]
  pull_request_target:
    branches: [main]
    types:
      - opened
      - reopened
      - synchronize
      - closed # This is important for the ghpage preview to clean up after itself

# Newer commits should cancel old runs
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        if: github.event_name == 'pull_request_target'
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          submodules: recursive
      - uses: actions/checkout@v4
        if: github.event_name == 'push'
        with:
          submodules: recursive
      # - uses: actions/setup-python@v5
      #   with:
      #     python-version: "3.8"
      # - uses: jwlawson/actions-setup-cmake@v2
      #   with:
      #     cmake-version: "3.28"
      # - name: Install dependencies
      #   run: |
      #     sudo apt install graphviz lcov
      #     pip install -r requirements.txt
      #     pip install torch==2.2.2
      # - name: Configure documentation
      #   run: |
      #     cmake \
      #       -DCMAKE_BUILD_TYPE=Coverage \
      #       -DCMAKE_UNITY_BUILD=ON \
      #       -DNEML2_TESTS=ON \
      #       -DNEML2_UNIT=ON \
      #       -DNEML2_REGRESSION=OFF \
      #       -DNEML2_VERIFICATION=OFF \
      #       -DNEML2_RUNNER=OFF \
      #       -DNEML2_PYBIND=ON \
      #       -DNEML2_DOC=ON \
      #       -B build \
      #       .
      # - name: Build documentation
      #   run: cmake --build build --target html -j 2 --
      # - name: Show build logs for C++ documentation
      #   run: cat build/doc/doxygen.html.log
      # - name: Show build logs for Python documentation
      #   run: cat build/doc/doxygen.python.log
      # - name: Show objects with missing documentation
      #   run: cat build/doc/syntax_error.log
      # - name: Error if syntax errors were detected
      #   run: grep -q "No syntax error" build/doc/syntax_error.log
      # - name: Build unit tests
      #   run: cmake --build build --target all -j 2 --
      # - name: Code coverage check
      #   run: |
      #     build/scripts/coverage.sh
      #     mv build/coverage build/doc/build/html/
      - name: Fake build
        run: |
          mkdir -p build/doc/build/html
          echo "This is a fake build" > build/doc/build/html/index.html
      - name: Preview GitHub Pages
        if: github.event_name == 'pull_request_target'
        uses: rossjrw/pr-preview-action@v1
        with:
          source-dir: build/doc/build/html
      - name: Deploy to GitHub Pages
        if: github.event_name == 'push'
        uses: JamesIves/github-pages-deploy-action@v4.4.1
        with:
          branch: gh-pages
          folder: build/doc/build/html
          clean-exclude: pr-preview/
          force: false
