name: Copyright

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-python@v6
        with:
          # dependencies: python.version_min
          python-version: "3.10"
      - name: Check to see if source files have the correct copyright header
        run: ./scripts/check_copyright.py
