name: Deploy documentation

on:
  workflow_run:
    workflows: ["Build documentation"]
    types:
      - completed

jobs:
  preview:
    runs-on: ubuntu-latest
    if: >
      github.event.workflow_run.event == 'pull_request'
    steps:
      - uses: actions/checkout@v4
      - name: Download documentation
        uses: dawidd6/action-download-artifact@v6
        with:
          workflow: build_docs.yml
          workflow_conclusion: success
          name: doc-${{ github.sha }}
          path: html
      - name: Preview GitHub Pages
        uses: rossjrw/pr-preview-action@v1
        with:
          source-dir: html
  deploy:
    runs-on: ubuntu-latest
    if: >
      github.event.workflow_run.event == 'push'
    steps:
      - uses: actions/checkout@v4
      - name: Download documentation
        uses: dawidd6/action-download-artifact@v6
        with:
          workflow: build_docs.yml
          workflow_conclusion: success
          name: doc-${{ github.sha }}
          path: html
      - name: Deploy GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4.4.1
        with:
          branch: gh-pages
          folder: html
          clean-exclude: pr-preview/
          force: false
