name: Python package

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  release:
    types:
      - published

# Newer commits should cancel old runs
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          # dependencies: python.version_min
          python-version: "3.10"
      - name: Run ruff lint
        uses: pre-commit/action@v3.0.1
        with:
          extra_args: ruff --all-files
      - name: Run ruff format check
        uses: pre-commit/action@v3.0.1
        with:
          extra_args: ruff-format --all-files
      - name: Run nmhit-format check
        uses: pre-commit/action@v3.0.1
        with:
          extra_args: nmhit-format --all-files

  typecheck:
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/neml2-ci
        with:
          # dependencies: python.version_min
          python-version: "3.10"
          # dependencies: cmake.version_min
          cmake-version: "3.26.1"
          # dependencies: torch.version
          torch-version: "2.12.0"
          cpu-torch: true
      - name: Install
        run: pip install ".[dev]" -v
      - name: Generate Python stubs
        run: neml2-stub
      - name: Run pyright
        run: pyright

  test:
    needs: lint
    strategy:
      fail-fast: false
      matrix:
        runner: [ubuntu-latest, macos-latest, gpu_runner]
    runs-on: ${{ matrix.runner }}
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/neml2-ci
        with:
          # dependencies: python.version_min
          python-version: "3.10"
          # dependencies: cmake.version_min
          cmake-version: "3.26.1"
          # dependencies: torch.version
          torch-version: "2.12.0"
          cpu-torch: ${{ matrix.runner != 'gpu_runner' }}
      - name: Install
        run: pip install ".[dev]" -v
      - name: Run tests
        run: pytest -v --junitxml=pytest.xml python/tests
      - name: Test results
        uses: EnricoMi/publish-unit-test-result-action/linux@v2
        if: always()
        with:
          files: pytest.xml
          check_name: Test Results
          check_run: false
          action_fail: true
          comment_mode: off

  wheels:
    needs: lint
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Free disk space
        if: runner.os == 'Linux'
        uses: jlumbroso/free-disk-space@main
        with:
          tool-cache: false
          android: true
          dotnet: true
          haskell: true
          large-packages: true
          swap-storage: true
      - name: Install cibuildwheel
        run: pip install cibuildwheel
      - name: Build wheels
        run: cibuildwheel --output-dir wheelhouse
        env:
          CIBW_BUILD: ${{ github.event_name == 'release' && 'cp310-* cp311-* cp312-* cp313-* cp314-*' || 'cp310-* cp314-*' }}
      - uses: actions/upload-artifact@v4
        if: github.event_name == 'release' && github.event.action == 'published'
        with:
          name: packages-wheels-${{ matrix.os }}
          path: wheelhouse/*.whl

  sdist:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build SDist
        run: pipx run build --sdist
      - name: Upload SDist
        uses: actions/upload-artifact@v4
        if: github.event_name == 'release' && github.event.action == 'published'
        with:
          name: package-sdist
          path: dist/*.tar.gz

  PyPI:
    needs: [sdist, wheels]
    environment: pypi
    permissions:
      id-token: write
    runs-on: ubuntu-latest
    if: github.event_name == 'release' && github.event.action == 'published'
    steps:
      - uses: actions/download-artifact@v4
        with:
          pattern: package-sdist
          path: dist
          merge-multiple: true
      - uses: actions/download-artifact@v4
        with:
          pattern: packages-wheels-*
          path: dist
          merge-multiple: true
      - uses: pypa/gh-action-pypi-publish@release/v1
