name: tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  schedule:
    - cron: '0 0 * * 0'

permissions:
  contents: read  # Required when overriding permissions
  pull-requests: write  # For posting coverage report

jobs:
  clang-format:
    name: Formatting Check
    runs-on: ubuntu-latest
    strategy:
      matrix:
        path:
          - "src"
          - "include"
          - "tests"
    steps:
      - uses: actions/checkout@v3
      - name: Run clang-format style check
        uses: jidicula/clang-format-action@v4.10.1
        with:
          clang-format-version: "14"
          check-path: ${{ matrix.path }}
  copyright:
    name: Copyright check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Check to see if source files have the correct copyright header
        run: python scripts/check_copyright.py
  build-test:
    needs: clang-format
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        btype: [Release, Debug]
        unity: [ON, OFF]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - run: |
          cmake \
            -DCMAKE_BUILD_TYPE=${{ matrix.btype }} \
            -DCMAKE_UNITY_BUILD=${{ matrix.unity }} \
            -DNEML2_UNIT=ON \
            -DNEML2_REGRESSION=ON \
            -DNEML2_VERIFICATION=ON \
            -DNEML2_BENCHMARK=OFF \
            -DNEML2_PROFILING=OFF \
            -DNEML2_DOC=OFF \
            .
      - run: make -j 2
      - run: make test
  build-all:
    needs: clang-format
    runs-on: ubuntu-latest
    strategy:
      matrix:
        btype: [Release, Debug]
        unity: [ON, OFF]
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - run: |
          cmake \
            -DCMAKE_BUILD_TYPE=${{ matrix.btype }} \
            -DCMAKE_UNITY_BUILD=${{ matrix.unity }} \
            -DNEML2_UNIT=ON \
            -DNEML2_REGRESSION=ON \
            -DNEML2_VERIFICATION=ON \
            -DNEML2_BENCHMARK=ON \
            -DNEML2_PROFILING=ON \
            -DNEML2_DOC=OFF \
            .
      - run: make -j 2
  coverage:
    name: Code coverage check
    needs: build-test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - run: sudo apt install lcov
      - run: |
          cmake \
            -DCMAKE_BUILD_TYPE=Coverage \
            -DCMAKE_UNITY_BUILD=OFF \
            -DNEML2_UNIT=ON \
            -DNEML2_REGRESSION=ON \
            -DNEML2_VERIFICATION=ON \
            -DNEML2_BENCHMARK=OFF \
            -DNEML2_PROFILING=OFF \
            -DNEML2_DOC=OFF \
            .
      - run: make -j 2
      - run: ./scripts/coverage.sh
      - uses: romeovs/lcov-reporter-action@v0.2.19
        with:
          lcov-file: ./coverage/coverage.info
          github-token: ${{ secrets.PR_ACTION }}
  cmake-integration:
    name: Test CMake integration as a subproject
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
          path: neml2
      - run: |
          echo "#include \"neml2/base/Registry.h\"" > main.cxx
          echo "using namespace neml2;" > main.cxx
          echo "int main(int argc, char * argv[]) {" > main.cxx
          echo "  std::cout << neml2::Registry::expected_options(\"ScalarSumModel\") << std::endl;" > main.cxx
          echo "  return 0;" > main.cxx
          echo "}" > main.cxx
      - run: cat main.cxx
      - run: |
          echo "project(FOO)" > CMakeLists.txt
          echo "add_subdirectory(neml2)" > CMakeLists.txt
          echo "add_executable(foo main.cxx)" > CMakeLists.txt
          echo "target_link_libraries(foo neml2)" > CMakeLists.txt
      - run: cat CMakeLists.txt
      - run: cmake -DCMAKE_BUILD_TYPE=Release -DBUILD_TESTING=OFF -B build .
      - run: cd build && ./foo

